### PR TITLE
Improve matrix transpose performance

### PR DESCRIPTION
**Pull request by szhorvat**
Improves the performance of `igraph_matrix_transpose()`.

Motivation: Mathematica uses row-major storage, which is different from igraph's column-major choice. Currently, the approach I use for transferring matrices is a direct copy of the underlying data followed by transposition. Thus, transpose performance impacts every functions that operates with matrices. Yesterday, `igraph_matrix_init_array()` was added, but right now it only supports column-major storage. It would make sense to support row-major storage as well. To add that feature, we need to perform the same operation as in transposition. Before doing that, let's figure out how to improve transpose performance.

Unless noted otherwise, all benchmarks below will be with shared libs, LTO enabled, Apple Clang 11, macOS on Intel.

### CODE REVIEW

**Comment by szhorvat** [comment]
Benchmark results from current version:

```
| Transpose    30 x    30, 100000x                                                 0.669s  0.665s  0.002s
| Transpose   100 x   100, 10000x                                                  0.708s  0.703s  0.003s
| Transpose  1000 x  1000, 100x                                                      1.1s   1.09s  0.003s
| Transpose  3000 x  3000, 10x                                                      1.13s   1.07s  0.053s
| Transpose   100 x 10000, 100x                                                    0.906s  0.903s  0.001s
| Transpose 10000 x   100, 100x                                                     0.91s  0.906s  0.002s
```

**Comment by szhorvat** [comment]
After the last commit, I get this. The level of improvement is too good to be true, can you take a quick look @ntamas, and confirm I didn't mess up anything?

```
| Transpose    30 x    30, 100000x                                                 0.051s  0.051s      0s
| Transpose   100 x   100, 10000x                                                  0.057s  0.055s  0.002s
| Transpose  1000 x  1000, 100x                                                    0.341s  0.337s  0.003s
| Transpose  3000 x  3000, 10x                                                     0.649s  0.585s  0.063s
| Transpose   100 x 10000, 100x                                                    0.249s  0.248s  0.001s
| Transpose 10000 x   100, 100x                                                    0.249s  0.248s  0.001s
```

**Comment by szhorvat** [comment]
The above commit adds blocking like at https://stackoverflow.com/q/5200338/695132

Benchmarks for different block sizes:

### bs=1

```
| Transpose    30 x    30, 100000x                                                 0.051s   0.05s      0s
| Transpose   100 x   100, 10000x                                                  0.061s  0.059s  0.002s
| Transpose  1000 x  1000, 100x                                                    0.342s  0.338s  0.003s
| Transpose  3000 x  3000, 10x                                                     0.738s  0.685s  0.053s
| Transpose   100 x 10000, 100x                                                     0.25s   0.25s  0.001s
| Transpose 10000 x   100, 100x                                                    0.247s  0.246s  0.001s
```

### bs=2

```
| Transpose    30 x    30, 100000x                                                 0.046s  0.045s      0s
| Transpose   100 x   100, 10000x                                                  0.077s  0.076s  0.002s
| Transpose  1000 x  1000, 100x                                                    0.222s  0.218s  0.003s
| Transpose  3000 x  3000, 10x                                                     0.398s  0.334s  0.063s
| Transpose   100 x 10000, 100x                                                    0.224s  0.223s  0.001s
| Transpose 10000 x   100, 100x                                                     0.22s  0.219s  0.001s
```

### bs=4

```
| Transpose    30 x    30, 100000x                                                 0.054s  0.053s      0s
| Transpose   100 x   100, 10000x                                                  0.075s  0.073s  0.002s
| Transpose  1000 x  1000, 100x                                                    0.217s  0.214s  0.003s
| Transpose  3000 x  3000, 10x                                                     0.284s  0.222s  0.063s
| Transpose   100 x 10000, 100x                                                    0.197s  0.197s      0s
| Transpose 10000 x   100, 100x                                                    0.206s  0.205s  0.001s
```

### bs=8

```
| Transpose    30 x    30, 100000x                                                 0.055s  0.054s      0s
| Transpose   100 x   100, 10000x                                                  0.076s  0.073s  0.002s
| Transpose  1000 x  1000, 100x                                                    0.218s  0.216s  0.002s
| Transpose  3000 x  3000, 10x                                                       0.3s  0.231s  0.069s
| Transpose   100 x 10000, 100x                                                    0.229s  0.227s  0.001s
| Transpose 10000 x   100, 100x                                                    0.239s  0.237s  0.001s
```

### bs=16

```
| Transpose    30 x    30, 100000x                                                 0.068s  0.067s      0s
| Transpose   100 x   100, 10000x                                                  0.075s  0.073s  0.002s
| Transpose  1000 x  1000, 100x                                                    0.248s  0.244s  0.003s
| Transpose  3000 x  3000, 10x                                                     0.336s  0.264s  0.072s
| Transpose   100 x 10000, 100x                                                    0.267s  0.266s  0.001s
| Transpose 10000 x   100, 100x                                                    0.289s  0.287s  0.001s
```

Note that the timings are not very stable on my machine.

**Comment by ntamas** [comment]
> Yesterday, igraph_matrix_init_array() was added, but right now it only supports column-major storage. It would make sense to support row-major storage as well. 

It was added because I needed a quick way  in the new Python interface to copy the contents of a NumPy array into an igraph matrix and vice versa.

Also, I went through the code in this PR and it seems correct. The original implementation was definitely suboptimal due to the modulo operation.

**Comment by szhorvat** [comment]
@ntamas I propose that we factor out the implementation from this PR as a separate internal transpose_and_copy function and use it both in transpose and in a new row-major mode of matrix_init_array. OK if I go ahead?

Additionally, I might try to add an in-place mode for transposing square matrices. That's the most common use case and hopefully it'll have even better performance.

**Comment by ntamas** [comment]
> OK if I go ahead?

Yes, sure, go ahead (with both suggestions)!

**Comment by szhorvat** [comment]
For the 3000 by 3000 case, Mathematica's transpose is still 2.2 times faster than this implementation, which shows what is possible. It probably uses the MKL internally.

**Comment by szhorvat** [comment]
Please don't merge yet. I want to implement in-place transpose for symmetric matrices first.

**Comment by szhorvat** [comment]
```
| Transpose    30 x    30, 100000x                                                 0.032s  0.031s      0s
| Transpose   100 x   100, 10000x                                                  0.033s  0.033s      0s
| Transpose  1000 x  1000, 100x                                                    0.077s  0.077s      0s
| Transpose  1024 x  1024, 100x                                                    0.106s  0.106s      0s
| Transpose  1023 x  1025, 100x                                                    0.281s  0.276s  0.004s
| Transpose  3000 x  3000, 10x                                                     0.126s  0.125s      0s
| Transpose   100 x 10000, 100x                                                    0.275s  0.249s  0.025s
| Transpose 10000 x   100, 100x                                                    0.242s  0.219s  0.022s
```

**Review by ntamas — APPROVED** [review]

**Pull request merged**
