### PR TITLE
add layout_kamada_kawai unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
Based on the fruchterman_reingold tests. When I printed out the values they also seemed ok.

### CODE REVIEW

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
Thanks! (And with this PR, coverage passes 80% for the first time ever).

**Comment by szhorvat** [comment]
Could you please include one more test for a graph with two connected vertices? I fixed a bug recently for this case.

**Comment by GroteGnoom** [comment]
https://github.com/igraph/igraph/commit/278904e027f4c2edd71385400043948c867d0e79

If I chose a ridiculous kkconst I could get the result out of the bounding box, but I can't really find any NaNs.

**Comment by szhorvat** [comment]
Thanks for the test expansion! I wouldn't put extreme values for `kkconst`. The problem appeared with the default value as well. Let's just put a reasonable value there, and keep the test as is otherwise.

**Pull request merged**
