### PR TITLE
Use correct `arpack_defaults()` default

### PR DESCRIPTION
**Pull request by krlmlr**
I wonder if the C core is really the right place for this configuration.

This would have to be forward-ported to the main branch too.

### CODE REVIEW

**Comment by szhorvat** [comment]
For now, let's do whatever is necessary to get the R release out. The `release/0.9` branch exists mostly for the benefit of R/igraph anyway.

In the longer term, there should be a proper solution that doesn't involve writing R-specific expressions, and can be handled from multiple languages.

**Comment by krlmlr** [comment]
This should also find its way into the mainline because https://github.com/igraph/rigraph/pull/840 relies on it.

**Comment by szhorvat** [comment]
Yes, and there it may interfere with the new Python interface, so let's wait for @ntamas.

In the long term we'll definitely need something more structured. We'll need to avoid writing R code or Python code in `functions.yaml`, or just relying on R and Python code looking the same. Mathematica code will definitely not look the same: underscores are not allowed in function names and function calls don't use parentheses.

But for the moment, the priority is to get the new R release out, not to have a perfect solution here.

**Comment by szhorvat** [comment]
Eventually, on the R side, `arpack_defaults()` should probably rely on `igraph_arpack_options_init()`, to make sure that different interfaces use the same default parameters. That's probably a bit messy to do at the moment.

**Comment by ntamas** [comment]
> In the longer term, there should be a proper solution that doesn't involve writing R-specific expressions,

`stimulus` treats the default values in an abstract manner and you can map them to real target-language-specific constructs in `types.yaml` like this:

```yaml
ARPACK_OPTIONS:
    DEFAULT:
        some_abstract_value: arpack_options()
```

So we can use a language-agnostic construct like `default_arpack_options` and then map it to whatever the target language supports in a language-specific `types.yaml` file.

**Comment by szhorvat** [comment]
No longer needed, this was handled according to Tamás's suggestion.

**Pull request closed without merging**
