### PR TITLE
Added fuzzer to integrate igraph into OSS-fuzz

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds a fuzzer with build script to run it continuously through OSS-fuzz.

Fuzzing is a way of testing programs whereby pseudo-random data is passed to a target application with the goal of finding bugs and vulnerabilities. I can see that igraph previously has been fuzzed by the community.

OSS-fuzz is a project by Google into which open-source projects can integrate and have their fuzzers run continuously. If bugs are found, maintainers get notified with an email containing a link to a detailed bug report with stack trace and reproducible test case.

I will shortly set up the integration on the OSS-fuzz side. All that is needed to complete the integration is to:

1. Merge in the files in this PR
2. Add at least one maintainers email address for potential bug reports.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
The integration files on the OSS-fuzz side have been added here: https://github.com/google/oss-fuzz/pull/4877

**Comment by szhorvat** [comment]
Hello @AdamKorcz, thanks for this nice contribution! Currently, all development happens on the `develop` branch, which will become igraph 0.9. We have switched to a CMake-based build system. Build instructions are roughly: 

```
mkdir build && cd build
cmake ..
make
```

More info [here](https://igraph.discourse.group/t/draft-document-for-installation-with-cmake/504).

`libigraph.a` is created in `build/src`.

Would you be able to re-base this PR against `develop` and make sure that oss-fuzzer uses that branch?

**Comment by szhorvat** [comment]
Alternatively, we can do it on `master` first then I'll merge this into `develop` with all the necessary changes. I'll get back to this later today. Feel free to add my email (as shown in GitHub) in the other PR. Perhaps @ntamas would prefer his to be included as well?

**Comment by AdamKorcz** [comment]
I would be happy to merge this is an the merge it into master. I will get your email address added @szhorvat

**Comment by AdamKorcz** [comment]
Closing to reopen

**Comment by szhorvat** [comment]
@AdamKorcz Why did you use `if(size<5) return 0;`? I would like to understand if there is any good reason for this before adding more fuzzers.

**Comment by AdamKorcz** [comment]
> @AdamKorcz Why did you use `if(size<5) return 0;`? I would like to understand if there is any good reason for this before adding more fuzzers.

Generally there may be some false positives in the case of short byte arrays. I cannot remember whether it applies to igraph though. If you add more fuzzers, you might be able to leave that out.

**Comment by szhorvat** [comment]
@AdamKorcz I removed the limits and so far everything seems to be good.

Another question:

Do you know why [this performance report](https://oss-fuzz.com/performance-report/libFuzzer_igraph_bliss_fuzzer/libfuzzer_asan_igraph/latest) complains about logging? The log files linked from the report do not contain any messages written by the program. In fact I do not think this program is outputting anything at all (or at least it shouldn't).

**Comment by szhorvat** [comment]
@AdamKorcz Is there a way to completely remove any generated corpus for a target and start from zero again?

I was experimenting with adding targets for some of the more complicated functions that process graphs. These need to receive the graph in some appropriate binary format that the fuzzer can mutate in a useful way. I think my first attempt was not very successful, and the graph format should be changed. This would make any existing corpus useless.

(In fact, I am not sure that fuzzing such functions is useful at all, even with a better input format and custom mutators. But it's always worth experimenting a bit. If you don't seek, you won't find anything.)

**Pull request closed without merging**
