### PR TITLE
install cmake files in ${CMAKE_INSTALL_LIBDIR}

### PR DESCRIPTION
**Pull request by kloczek**
cmake files shoud be installed in ${CMAKE_INSTALL_LIBDIR}/cmake/<project>

Signed-off-by: Your Name <you@example.com>

### CODE REVIEW

**Comment by kloczek** [comment]
Path is not fixing all install cmake fiels entries.
Will fix that patch later

**Comment by szhorvat** [comment]
@kloczek Try to make the change on line 499 as well.

**Comment by ntamas** [comment]
Makes sense to me; indeed, I should have used `${CMAKE_INSTALL_LIBDIR}`. Once the PR fixes all such occurrences I'll happily merge it.

**Comment by szhorvat** [comment]
@kloczek Can you please report back about whether this resolves your issue after fixing line 499?

**Comment by kloczek** [comment]
On sec :)

**Comment by kloczek** [comment]
Closing. Correct patch is in https://github.com/igraph/igraph/pull/1767

**Pull request closed without merging**
