### PR TITLE
Add igraph_get_incidence unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of #1592

### CODE REVIEW

**Comment by szhorvat** [comment]
I would opt for issuing a warning instead of an error, and simply ignoring edges that connect vertices within the same partition.

**Comment by szhorvat** [comment]
(I fixed the doc failure on master now.)

**Comment by ntamas** [comment]
> I would opt for issuing a warning instead of an error

In that case, we should probably count how many such edges there are, and just report _one_ warning at the end of the routine with the number of non-bipartite edges.

**Comment by szhorvat** [comment]
Yes, that, or if we want to keep it simple, then we can also omit the number, and just use a flag to determine if the warning was already reported. Let's get this in before 0.9.3.

**Comment by szhorvat** [comment]
Another thought: do not say "not bipartite", but say "n edges running within partitions were ignored" or something similar.  The graph may be bipartite, but the supplied types vector may not be consistent with the two partitions.

**Comment by ntamas** [comment]
Fixed wording; "independent sets" has another meaning in graph theory so I've removed that part.

**Comment by GroteGnoom** [comment]
I thought I was using this definition: https://en.wikipedia.org/wiki/Independent_set_(graph_theory)

**Comment by ntamas** [comment]
Indeed that's the definition I was thinking about, you are right. I can't quite put my finger on what bothered me with the original message; somehow it felt confusing. Sorry :)

**Comment by szhorvat** [comment]
I was slightly confused too at first, but the usage was perfectly correct.

**Pull request merged**
