### PR TITLE
Add lapack_dgetrf unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of #1592

### CODE REVIEW

**Comment by GroteGnoom** [comment]
@szhorvat Does https://github.com/igraph/igraph/commit/c218f4b6ef7d49297cbcbabfb42b1e7741edffa1 cause 0.00000 to be printed out as 0.000000 on windows?

**Comment by szhorvat** [comment]
Yes, MSVC bug. https://stackoverflow.com/q/65900619/695132 

I noticed it a while ago (#1634), but for some reason (that I still don't understand) it didn't affect the CI until I changed to use the Ninja generator today. It might be a Release vs Debug mode thing, not sure.

I'll fix this in some way tonight.

**Comment by szhorvat** [comment]
You can now merge `develop` into this branch (or rebase it) to get rid of the test failures

**Comment by szhorvat** [comment]
@GroteGnoom When you fix a bug (as here—the function didn't allocate the proper memory for the `ipiv` vector), please do add a note to the PR, to make it easier to write the changelog later.

**Pull request merged**
