### PR TITLE
fix original issue #580 not propagated to 0.7.1 release

### PR DESCRIPTION
**Pull request by EmSyndio**
see: 
https://github.com/igraph/igraph/issues/580

### CODE REVIEW

**Comment by EmSyndio** [comment]
Could you possibly cut a new release though?
Thanks

**Comment by ntamas** [comment]
I cannot make a release on my own. @gaborcsardi?

**Comment by szhorvat** [comment]
Making a new release is a big undertaking. There were a large number of new functions added, API changes, etc.

Personally, I would prefer if you could wait until I can submit a complete pull request for transitioning everything to the new (fast) maximal clique finder. That would also make pull request #824 obsolete.  However, I can't promise to be able to finish that before ~2 months from now.

I wish I could also finish the LAD update (which will certainly make more API changes necessary), but I don't think I will have enough time for that ...

**Comment by szhorvat** [comment]
Or maybe I misunderstood and this was a request for a 0.7.2 bugfix release instead of a new 0.8 one?

**Comment by ntamas** [comment]
Yes, it's a request for 0.7.2. In theory, 0.7.2 could be released easily because the changes in this pull request were merged into the `release-0.7` branch and not the master branch, so the only thing that changed between 0.7.1 and 0.7.2 is this fix (as far as I know).

**Comment by szhorvat** [comment]
Then disregard my comment please. It does not apply to this situation.

**Comment by EmSyndio** [comment]
Just confirming here: 

This PR is to incorporate the Burt's constraint bug fix in the 0.7.x release.

This bug fix was supposed to be in 0.7.1 as per the release notes, but it was not.
The PR just remerged the bug fix into release-0.7 branch.
A new release should simply be about tagging and creating a release from that branch.

Personally, I just want to be able to use Burt on the latest stable official release (i.e. pull the tar file and build) and not have to patch it myself before building, diverging from official release.

Thanks

**Comment by EmSyndio** [comment]
still no new release for this... :-(

@gaborcsardi?

**Comment by vtraag** [comment]
Shall we close this @ntamas @szhorvat @iosonofabio, since it is already merged in master, and we will not update `release-0.7` any further?

**Comment by ntamas** [comment]
Not much to do there; this is a merged PR and #580 is already closed.

**Comment by vtraag** [comment]
Ah yes, sorry.

**Pull request merged**
