### PR TITLE
More doc fixes

### PR DESCRIPTION
**Pull request by szhorvat**
Include docs for igraph_local_scan* functions

### CODE REVIEW

**Comment by szhorvat** [comment]
@ntamas Ready to merge and after you do, can you please re-build the website? I think this completes as much of #1297 as reasonable for 0.8

**Comment by ntamas** [comment]
Build is underway; it should be rsynced in 15 mins or so.

**Comment by ntamas** [comment]
Sorry, will do this tomorrow in the morning instead

**Comment by ntamas** [comment]
Docs updated.

**Pull request merged**
