### PR TITLE
Implement CI tests on windows (appveyor)

### PR DESCRIPTION
**Pull request by janschulz**
Currently WIP... I'm currently trying it in my own fork with my account: https://ci.appveyor.com/project/JanSchulz/igraph/

In the end, it needs appveyor enabling in this project: an owner in this project needs to get a appveyor account and enable the project in the appveyor UI. 

I also suspect that the msvc tests will not build due to https://github.com/igraph/igraph/issues/909#issuecomment-230936503

### CODE REVIEW

**Comment by ntamas** [comment]
Added `igraph` to my AppVeyor account - what else do I need to do? Shall I just merge this pull request and see how the build goes?

**Comment by janschulz** [comment]
I think you are done: it will just build every PR and if appveyor doesn't find an appveyor.yml file will skip that build. So new commits in this PR should be build, but all other PRs/commits not (until this PR is merged). We will see when I push a commit to this PR, I'm currently waiting for https://ci.appveyor.com/project/JanSchulz/igraph/build/job/6nhpxyacxv273x4r :-)

**Comment by janschulz** [comment]
And there it is :-)

**Comment by janschulz** [comment]
Autsch: [31 minutes](https://ci.appveyor.com/project/JanSchulz/igraph/build/1.0.9) just for one msys2 build, so the complete tests will take over 3h... I should probably implement that as one msys2 build+test and 3 msvc builds...

**Comment by janschulz** [comment]
@ntamas could you kill all appveyor builds other than the latest? I screwed up with the `conda update conda` call and now all these builds will wait on updating the root python (at worst case 1h until the timeout) :-(

**Comment by ntamas** [comment]
Done.

**Comment by janschulz** [comment]
Ok, py27 starts building but fails https://ci.appveyor.com/project/ntamas/igraph/build/job/mt81sistwbvl1gq2

For the rest, I have to see how to properly start it :-(

**Comment by ntamas** [comment]
I have started looking for `: error` in the compiler output and started fixing things, but I have to go now. It looks like there are many compilation errors stemming from the fact that MSVC doesn't "like" variable declarations being mixed with code and these errors can be fixed easily by moving the variable declarations up to the start of the closest code block (see my two most recent commits).

**Comment by janschulz** [comment]
Rebased on top of master, lets see what is still failing...

**Comment by janschulz** [comment]
@ntamas layout_gem contains a line referencing `M_PI_2`, but I found no line declaring or setting it. This seems like a bug :-/ https://github.com/igraph/igraph/blob/19946d044c4b6ad7aa6f917d312453a83d8a7e6d/src/layout_gem.c#L211

**Comment by janschulz** [comment]
If the last two builds ("Appveyor: use devenv instead of VCUpgrade" and "Add artifacts to appveyor" hand :-( It would be great if someone could kill the builds... I currently use my own account to test further builds...

**Comment by gaborcsardi** [comment]
Only Tamas can admin it, afaik.

**Comment by janschulz** [comment]
Also seems not to matter: the devenv call also freezes without the "overwrite"... Seems this problem needs a new `igraph.vcxproj` so that this can happen without the upgrade step :-(

**Comment by ntamas** [comment]
Just came online and it seems like there are no more builds in progress... is there anything else I should do? (Thanks for the `M_PI_2` fix by the way).

**Comment by janschulz** [comment]
so, the py35 error is now 

> The following error has occurred during XML parsing: File: C:\data\external\igraph\igraph-0.8.0-pre+81ed709-msvc\igraph.vcproj Line: 3477 Column: 0 Error Message: Systemfehler: -2146233079. The file 'C:\data\external\igraph\igraph-0.8.0-pre+81ed709-msvc\igraph.vcproj' has failed to load.

If anyone has an clue... :-/

**Comment by janschulz** [comment]
@ntamas right now I'm stuck with converting the project file on py34 and py35 and the py27 build fails to set the right include dirs so that the  vendored source files find their *.h files.

**Comment by janschulz** [comment]
Ok, found a hint:

```
 <File
                               RelativePath=".\include\make[1]:"
                               FileType="2">
                       </File>
                       <File
                               RelativePath=".\include\Leaving"
                               FileType="2">
                       </File>
                       <File
                               RelativePath=".\include\directory"
                               FileType="2">
                       </File>
```

This looks wrong...

**Comment by ntamas** [comment]
Looks like a bug in our `tools/create-msvc-projectfile.py` script that creates the MSVC project file for the MSVC release.

**Comment by janschulz** [comment]
The "don't find the header" seems to be a problem that certain files don't show up in `echosources` makefile target, e.g. the ones under AMD, CHOLMOD and COLAMD: e.g. "colamd.h" is only included once as a source file, but not as a header :-(

**Comment by janschulz** [comment]
yay, finally I got all to build...

@ntamas @gaborcsardi Ok, now I'm out of ideas:

https://ci.appveyor.com/project/JanSchulz/igraph/build/1.0.43/job/pswkw57pt1u0tvsp (but py34 and py35 fail with similar errors)
```
.\src\CHOLMOD\Partition\cholmod_metis.c(55) : fatal error C1083: Cannot open include file: 'metis.h': No such file or directory
```

```
c:\data\external\igraph (appveyor)
[igraph35] λ grep -R metis.h
igraph-0.8.0-pre+81ed709-msvc/src/CHOLMOD/Partition/cholmod_metis.c:#include "metis.h"
src/CHOLMOD/Partition/cholmod_metis.c:#include "metis.h"

[igraph35] λ es metis.h
C:\portabel\R\R\win-library\3.3\BH\include\boost\graph\metis.hpp
C:\portabel\R\R\win-library\3.4\BH\include\boost\graph\metis.hpp
```

-> Ok, this seems to require boost, I can probably get that from msys2 somewhere, but no idea how to include it in 

```
.\src\CHOLMOD\Partition\cholmod_ccolamd.c(32) : fatal error C1083: Cannot open include file: 'ccolamd.h': No such file or directory
cholmod_camd.c
.\src\CHOLMOD\Partition\cholmod_camd.c(42) : fatal error C1083: Cannot open include file: 'camd.h': No such file or directory
cholmod_band.c
```

```
c:\data\external\igraph (appveyor)
[igraph35] λ grep -R ccolamd.h
igraph-0.8.0-pre+81ed709-msvc/src/CHOLMOD/Partition/cholmod_ccolamd.c:#include "ccolamd.h"
igraph-0.8.0-pre+81ed709-msvc/src/CHOLMOD/Partition/cholmod_csymamd.c:#include "ccolamd.h"
src/CHOLMOD/Partition/cholmod_ccolamd.c:#include "ccolamd.h"
src/CHOLMOD/Partition/cholmod_csymamd.c:#include "ccolamd.h"

c:\data\external\igraph (appveyor)
[igraph35] λ es ccolamd.h

[igraph35] λ grep -R camd.h |grep -v _camd.h
igraph-0.8.0-pre+81ed709-msvc/src/CHOLMOD/Partition/cholmod_camd.c:#include "camd.h"
src/CHOLMOD/Partition/cholmod_camd.c:#include "camd.h"

c:\data\external\igraph (appveyor)
[igraph35] λ es camd.h
C:\data\external\igraph\igraph-0.8.0-pre+81ed709-msvc\src\CHOLMOD\Include\cholmod_camd.h
C:\data\external\igraph\src\CHOLMOD\Include\cholmod_camd.h
```

-> The camd.h looks almost like a missed rename, but then both cholmod_camd.h and camd.h are included in that file right one after another. No idea about ccolamd.h... :-(

**Comment by janschulz** [comment]
WTF? Why does this NOT compile, but all the other files which include that file?

```
c:\projects\igraph\igraph-0.8.0-pre+2a13533-msvc\src\prpack\prpack_csc.h(4) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
```

**Comment by janschulz** [comment]
And more fun: 

https://ci.appveyor.com/project/ntamas/igraph/build/1.0.43/job/29qa3e24fpi77bh8#L3724
```
src\prpack.cpp(66): error C2065: 'prpack_igraph_graph' : undeclared identifier [C:\projects\igraph\igraph-0.8.0-pre+2a13533-msvc\igraph.vcxproj]
src\prpack.cpp(66): error C2146: syntax error : missing ';' before identifier 'prpack_graph' [C:\projects\igraph\igraph-0.8.0-pre+2a13533-msvc\igraph.vcxproj]
src\prpack.cpp(66): error C3861: 'prpack_graph': identifier not found [C:\projects\igraph\igraph-0.8.0-pre+2a13533-msvc\igraph.vcxproj]
src\prpack.cpp(67): error C2065: 'prpack_graph' : undeclared identifier [C:\projects\igraph\igraph-0.8.0-pre+2a13533-msvc\igraph.vcxproj]
```

https://ci.appveyor.com/project/ntamas/igraph/build/1.0.43/job/e0nih5t2qugwblp7#L4342

```
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(217): warning C4005: 'register': macro redefinition [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  c:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\src\gengraph_definitions.h(26): note: see previous definition of 'register'
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(250): fatal error C1189: #error:  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro. [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  gengraph_mr-connected.cpp
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(217): warning C4005: 'register': macro redefinition [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  c:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\src\gengraph_definitions.h(26): note: see previous definition of 'register'
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(250): fatal error C1189: #error:  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro. [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  gengraph_graph_molloy_optimized.cpp
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(217): warning C4005: 'register': macro redefinition [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  c:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\src\gengraph_definitions.h(26): note: see previous definition of 'register'
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(250): fatal error C1189: #error:  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro. [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  gengraph_graph_molloy_hash.cpp
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(217): warning C4005: 'register': macro redefinition [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
  c:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\src\gengraph_definitions.h(26): note: see previous definition of 'register'
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xkeycheck.h(250): fatal error C1189: #error:  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro. [C:\projects\igraph\igraph-0.8.0-pre+5efbd97-msvc\igraph.vcxproj]
```

So, currently all three msvc builds fail at a different place :-(

**Comment by janschulz** [comment]
Update: I managed to remove the problem with redefining register.  Now only two problems remain...

**Comment by ntamas** [comment]
> WTF? Why does this NOT compile, but all the other files which include that file?

MSVC does not have `stdint.h` so other files include this conditionally; see, e.g., `src/plfit/lbfgs.c`:

```
#ifndef _MSC_VER
#include <stdint.h>
#endif
```

We need `stdint.h` only to get `int64_t` (i.e. a 64-bit signed integer type). For MSVC, you can probably get around this by not including `stdint.h` and using this instead:

```
typedef __int64 int64_t;
```

**Comment by ntamas** [comment]
```
src\prpack.cpp(66): error C2146: syntax error : missing ';' before identifier 'prpack_graph' [C:\projects\igraph\igraph-0.8.0-pre+2a13533-msvc\igraph.vcxproj]
```

Can this be a problem with not defining `PRPACK_IGRAPH_SUPPORT` in the MSVC version of `config.h`?

**Comment by janschulz** [comment]
> Can this be a problem with not defining PRPACK_IGRAPH_SUPPORT in the MSVC version of config.h?

I do define it: https://github.com/igraph/igraph/pull/951/files#diff-3209138253bf6b677d8c22e3a2e1f66cR180 (commit: https://github.com/igraph/igraph/pull/951/commits/82a29ee6f5b799b1da71ec12a1bea616110d0448)

**Comment by janschulz** [comment]
... but prpack.cpp does not include config.h...

**Comment by janschulz** [comment]
And the first MSVC builds are green... yay! Will be interesting what the last builds spits out, thats the `make check` on msys2 (NOT msvc!).

**Comment by janschulz** [comment]
... and the tests *all* fail, so I suspect that something basic in the tests is failing... :-/

IMO the msvc building is something which could be merged right now. I can remove the make check into a different PR, if you want that...

**Comment by szhorvat** [comment]
Sorry if this is a too naive comment ... you are probably well aware of this.  But just in case: When you run tests on Windows, if you build igraph as a DLL you must make sure that the DLL is in the path.

**Comment by janschulz** [comment]
It seems that the testssuite is not going to work on windows, at least if I interprete https://github.com/igraph/igraph/blob/19946d044c4b6ad7aa6f917d312453a83d8a7e6d/tests/testsuite.at#L30
-> If that's shell command to set a path, then that sin't going to work :-( `LD_LIBRARY_PATH` is also probably not be used on windows.

**Comment by janschulz** [comment]
@szhorvat good idea! I've actually no clue how the tests work, so I'm mostly doing trial&error here :-/

**Comment by szhorvat** [comment]
I'm not fully following what you're doing here (sorry, too many comments to read :-) ), but I do build igraph (master branch) successfully with mingw-w64 + msys2.  I can also run the tests. There are some that fail due to different printing of floating point infinities, but there aren't any true problems.  https://github.com/igraph/igraph/issues/886

As I said earlier, I never managed with MSVC, so it's great that you're sorting that out.

**Comment by ntamas** [comment]
>  If that's shell command to set a path, then that isn't going to work :-( 

Yes; basically, the linker on Linux looks for `.so` files (the equivalents of DLLs) in some predefined places plus whatever directories you put in `LD_LIBRARY_PATH`. Mac OS X is the same but with `DYLD_LIBRARY_PATH`. The line that you pointed to sets up these environment variables to ensure that the tests are run with the version of igraph that was compiled.

As far as I know, the closest thing to these on Windows is the `PATH` variable. When looking for a DLL, Windows looks at the folder of the executable and the folders in the `PATH` variable (and probably some standard places). So, maybe you could get around this by setting the `PATH` to include the folder that contains the freshly built `igraph.dll` temporarily.

**Comment by janschulz** [comment]
Ok, I've set the PATH to the folder which has the dll, lets see if thats already enough to fix it :-)

**Comment by janschulz** [comment]
Ok, setting the PATH seems not be enough (or I messed up something there): https://ci.appveyor.com/project/ntamas/igraph/build/1.0.51/job/8j5f777fx1sn3ham

@szhorvat Could you paste here the commands you used to run the testsuite?

**Comment by janschulz** [comment]
seems that I messed something up? at least the new path didn't show up in the testsuite.log...

**Comment by szhorvat** [comment]
I'll tell you how I do it in in the evening (European time).

**Comment by janschulz** [comment]
@szhorvat thanks!

**Comment by szhorvat** [comment]
It doesn't look like I'll get to a Windows machine with msys2 today.  So here it is, partly from my notes, partly from memory.  This is probably not the "right way", and I don't claim to understand what I'm doing.  But it works, at least so far.  If you know how/when it might cause trouble, and how to fix that, please let me know.

First build gmp:

```
./configure --prefix=$HOME/local
make
make check
```

This builds the static library.  It produces an `.a` file and an `.la` file.  I'm installing everything into `$HOME/local`.

Now we build igraph.  I never build the graphml stuff because I don't need it, but I do need GMP.

For some reason that I don't understand, linking gmp statically fails since a few months ago (after an msys update).  If I delete the `.la` file, then linking succeeds and everything seems to work fine.  I don't know why and I welcome explanations.  So before building igraph, delete gmp's `.la` file.

Now in the igraph directory,

```
export CPPFLAGS="-I$HOME/local/include -DMSDOS" LDFLAGS=-L$HOME/local/lib
```

Defining `MSDOS` solves many problems and prevents trying to include UNIX-specific stuff that's no available in MinGW.  I don't remember the details, but I remember that when I looked into it, it seemed that this had to be defined on Windows (not on DOS!).  I also remember that originally @ntamas said that this seems DOS specific and shouldn't be used, but in the end I concluded that it wasn't so.  This is for some libraries that igraph (0.8 branch) relies on and ships with.

```
./bootstrap.sh
./configure --prefix=$HOME/local --disable-graphml
make
make install
```

Now add `$HOME/local/bin` to the `PATH` environment variable so programs can find the igraph DLL.

Now you can do `make check` and everything should succeed except for what I mentioned in #886 

I used msys2 from https://msys2.github.io/ and installed dependencies using instructions here: https://wiki.qt.io/MSYS2

This is how I build igraph to be used in the Mathematica interface.  Then I build the Mathematica interface using MSVC (2015).  To avoid ABI-incompatibility problems between MSVC and MinGW, it is important to use free/malloc in compatible pairs.  That's the reason for this pull request: https://github.com/igraph/igraph/pull/933 (already merged).

I know this looks like a mess, but it's the only way I could get things working in the amount of time I had to spend on this.

**Comment by szhorvat** [comment]
Someone should really write up a detailed guide for building with various toolchains ...

**Comment by janschulz** [comment]
And it worked. In then end it was my stupidity with setting PATH :-)

Thanks @szhorvat for the PATH hint! :-)

**Comment by szhorvat** [comment]
Can you give me any hints about how to make GMP link statically without messing with the `.la` file?

**Comment by janschulz** [comment]
@szhorvat I've actually no clue right now. I only managed to compile it because I wanted it compiled for the python port :-)

@ntamas @gaborcsardi it built, IMO this is ready to be merged :-)

**Comment by ntamas** [comment]
This is great job, thanks for all your hard work on this!

**Pull request merged**
