### PR TITLE
autoconf: EOL issue on Windows (testsuite)

### PR DESCRIPTION
**Pull request by jannick0**
With this commit series all tests pass on my Windows 10 machine (using MSYS2 MINGW64). 
Please run testse on other platforms, too, on OSX in particular (where `\r` is special). Thanks.

### CODE REVIEW

**Comment by szhorvat** [comment]
@ntamas Is it okay to use the Visual Studio 2019 image for AppVeyor? [It is claimed that it has a new (working) msys2.](https://help.appveyor.com/discussions/problems/27815-build-failing-due-to-key-error) I'm not so familiar with AppVeyor. We should somehow get it working again before merging this.

@jannick0 According to the Travis tests, it works on macOS and Linux.

**Comment by ntamas** [comment]
Totally fine; I'll try to switch the Appveyor image and then rebuild the CI tests for this PR. It looks like there's quite a bit of arcane autotools magic in there - thanks for the great job @jannick0!

**Comment by ntamas** [comment]
@szhorvat so it looks like we _are_ using the Visual Studio 2019 image already. I fixed things in `master` by importing the missing PGP key manually; it seems to work now.

I'll take a chance and merge this into `master` as is and see whether the CI checks pass there.

**Comment by jannick0** [comment]
Great - I am glad that everything runs smoothly now. Thanks, guys! Happy to close #1401.

**Comment by szhorvat** [comment]
I think we are having some problems with this on some more exotic platforms:

https://travis-ci.com/github/szhorvat/igraph/builds/178149534

**Comment by jannick0** [comment]
Uuuh, let me have a look.

**Comment by szhorvat** [comment]
@jannick0 The problem is that `fgetc` returns an `int` and `EOF` is generally an `int` not a `char`. We must change the type of `c` and `c_prev` into `int` in order to make it work.

**Comment by szhorvat** [comment]
I pushed a fix, let's see if the tests pass.

**Comment by jannick0** [comment]
OK - great. Thanks.  To be on the very safe side the while loop could be forced to be finite (e.g., using a counter).

**Comment by szhorvat** [comment]
it passes now: https://travis-ci.com/github/szhorvat/igraph/builds/178154491



>  To be on the very safe side the while loop could be forced to be finite (e.g., using a counter).

I think it's fine with the `while (1)`. An `EOF` *must* come up eventually. The problem was that the value returned by `fgetc` was implicitly cast to a `char`. The program worked on platforms where `char(EOF) == EOF`, but it failed on those where this is not the case. *Why exactly* this comparison happened to be `true` on x86, I don't understand ... but with the correct type for `c` and `c_prev` everything should be fine on all platforms.

**Comment by jannick0** [comment]
Yes, fully agree. Thanks!

**Pull request merged**
