### PR TITLE
Only use "name" (no "id") attribute in Pajek reader/writer

### PR DESCRIPTION
**Pull request by szhorvat**
This PR completely replaces the use of the "id" vertex attribute by the "name" attribute in the Pajek reader and writer.

Previously,

 - When reading Pajek files, vertex names were placed into both an "id" and a "name" attribute
 - When writing Pajek files, the "id" attribute was used for vertex names instead of the "name" attribute. High-level interfaces generally use "name" for identification.

See discussion starting here: https://github.com/igraph/rigraph/issues/511#issuecomment-1358981605

This is targeting `develop` because it can be considered a breaking change.

Before this is merged, we should check very carefully if there were any special reasons to not use "name". Perhaps there was an issue related to uniqueness considerations, but it was not documented. Note that the Pajek format does not use the words "name" and "id"—these are choices on the igraph side.

No hurry in merging this.

@ntamas I leave it to you whether any of this should be ported back to `master` (perhaps with better compatibility, such as retaining "id" in some cases. IMO it's not necessary.

### CODE REVIEW

**Comment by ntamas** [comment]
Notes for ourselves: it should be checked whether Pajek (i.e. the _desktop_ software, not the file format) attaches any special meaning to the `id` attribute or not.

**Comment by szhorvat** [comment]
Related: https://github.com/igraph/igraph/issues/495#issuecomment-19449397

The same change was requested, but rejected with the reasoning that it is breaking.

**Comment by ntamas** [comment]
Well, it wasn't _rejected_ per se, note that the issue was closed as fixed earlier than the comment suggesting the change. I just added a note to state that it's a breaking change (which it is).

**Comment by szhorvat** [comment]
Yes, didn't mean it in absolute terms, just trying to summarize. I was about to edit the comment when you responded.

Pajek seems to use the term "label" for what we are discussing as "vertex name" here in this issue: http://vladowiki.fmf.uni-lj.si/doku.php?id=pajek:faq:format

It's good to mention that the format does not seem to support arbitrary attribute names. There are some predefined attributes. So _I assume_ (but did not check) that the software also won't. The vertex number is referred to as "index" and is 1-based.

**Comment by szhorvat** [comment]
Rebased on latest `develop`.

**Comment by ntamas** [comment]
@szhorvat What shall we do with this? Shall we merge it as-is? Or shall we ask the Pajek authors at the workshop in June? (I believe someone is going to represent them).

**Comment by szhorvat** [comment]
@ntamas I think we should merge this for `develop`.

**Pull request merged**
