### PR TITLE
Bipartite havel hakimi construction 

### PR DESCRIPTION
**Pull request by larah19**
Added 
- Function _igraph_realize_bipartite_degree_sequence_ in degree_sequence.cpp which contains a bipartite havel hakimi construction.
- _bipartite_havel_hakimi.c_ under tests/unit

### CODE REVIEW

**Review by szhorvat — COMMENTED** [review]
I'm sorry, I forgot to post the partial review. I removed the comment that are no longer relevant after your changes, and posting only two small ones.

**Comment by szhorvat** [comment]
Hi @larah19, sorry that this took so long. Is there anything that we are still missing here? It all looks good to me. Thanks for working on this!

**Comment by szhorvat** [comment]
@ntamas, can you have a quick look before merging?  Be sure to use "squash-and-merge" when you do.

**Comment by larah19** [comment]
> Hi @larah19, sorry that this took so long. Is there anything that we are still missing here? It all looks good to me. Thanks for working on this!

Hi, no worries :)
I think I added everything we talked about when we last spoke, so if it looks good to you everything should be there :) 
Thanks for letting me participate!

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
Thank you both!

**Pull request merged**
