### PR TITLE
Bipartite stochastic block model community detection algorithm

### PR DESCRIPTION
**Pull request by ostrowr**
This pull request contains an implementation of the algorithm described in "Efficiently inferring community structure in bipartite networks" by Larremore et. al. (http://arxiv.org/abs/1403.2933)

Essentially, the algorithm takes the classical stochastic block model approach, and extends it to work well with bipartite networks. 

This implements `igraph_community_bipartite_sbm.c` along with basic documentation and linking. I also updated the test suite with a toy example, but haven't written a suitable test yet. 

Let me know what I should change to make sure that everything is in line with the igraph standard.

### CODE REVIEW

**Comment by ostrowr** [comment]
decided not to include?

**Comment by gaborcsardi** [comment]
No, no worries, just takes longer.....

**Comment by tekknolagi** [comment]
@gaborcsardi any plans to implement by chance?

**Comment by gaborcsardi** [comment]
Oh, man, I closed this by accident. :(

**Comment by tekknolagi** [comment]
Perhaps reopen?

**Comment by gaborcsardi** [comment]
I would, but interestingly enough, I can't. Maybe only @ostrowr can?

**Comment by gaborcsardi** [comment]
Oh, I see, @ostrowr deleted his branch.....

**Comment by tekknolagi** [comment]
@ostrowr reopen reopen reopen! :D

**Comment by tekknolagi** [comment]
Er, no he didn't: https://github.com/ostrowr/igraph/tree/ostrow_biSBM

**Comment by gaborcsardi** [comment]
Oh, actually, I deleted the `develop` branch. MAkes sense. @ostrowr needs to resubmit this against the `master` branch. But then it will not merge cleanly of course. :(

**Comment by ostrowr** [comment]
happy to try to rebase in the next couple days -- I remember you had plans for more native support for bipartite graphs. Did that ever end up happening? If so, this should probably be rewired to work with that. Otherwise, merge should be pretty straightforward.

**Comment by gaborcsardi** [comment]
I think it will be hard, because a lot of things have changed in the repos. But I am happy to sort things out. 

Maybe actually this issue was closed down automatically when I deleted the `develop` branch. At least I can't remember closing it.....

**Pull request closed without merging**
