### PR TITLE
Fixes igraph_is_graphical_degree_sequence for the undirected case

### PR DESCRIPTION
**Pull request by szhorvat**
The new undirected graphicality test based on Kiraly's paper was bugged, as I mentioned in https://github.com/igraph/igraph/issues/1432 This PR fixes the problem.

Changes:

 - fix `igraph_is_graphical_degree_sequence` for undirected case
 - explicitly check degree sequence for negative entries, and return "false" is any are found
 - add `igraph_vector_reverse_sort` (used in `igraph_is_graphical_degree_sequence`)
 - document `igraph_vector_reverse_sort` (we may remove the docs if we don't want to explicitly support a newly added function in a 0.8.x release)
 - remove claim that `igraph_vector_sort` was using `qsort` from the standard C library, as it is using `qsort.c` shipped with igraph

### CODE REVIEW

**Comment by szhorvat** [comment]
The problems were:

 - must sort deg. seq. decreasingly
 - the code did not use the sorted version at all
 - must check that sum of degrees is even

**Comment by szhorvat** [comment]
@ntamas Sorry about being a bit pushy, but the rest of PRs to come are condition on this. I'm happy to address even minor-sounding concerns. My priority is to correct the problem and move on.

**Comment by ntamas** [comment]
Sorry about the delay, we went on a short holiday break with the family and this fell through the cracks somehow. I'm merging it soon.

**Comment by szhorvat** [comment]
I messed up and duplicated one of the checks. Will send an extra PR soon.

**Comment by szhorvat** [comment]
Fixed here 8373efcb1d91352ad8a48c099b158be8c0f860c3

**Pull request merged**
