### PR TITLE
Add clique_size_hist unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of #1592

Bugfix: igraph_vector_resize_min used a Realloc, which returns NULL
 when called with 0 size, which was then interpreted as an error.
 A free and a calloc does not have the same problem, because calloc
 can return a pointer which can be properly freed, even when called
 with size 0. Calloc can also return NULL when called with size 0, but
 apparently doesn't do this, because else every vector_init with 0
 members would also have problems.

### CODE REVIEW

**Comment by vtraag** [comment]
This actually touches on a broader issue discussed in https://github.com/igraph/igraph/issues/1479, where it is noted that having arrays of size 0 are not always necessarily well-supported. We there discussed the possibility of fixing this in the `igraph_Calloc` and friends by ensuring a minimum allocation size of 1 (even though this need not be used in practice). Perhaps you could take a look at that problem?

**Comment by szhorvat** [comment]
@vtraag I was just going to summon you with a link to #1479 :-)

@GroteGnoom For all of malloc/calloc/realloc, the behaviour with a zero size is implementation defined, and cannot be relied on.

**Comment by szhorvat** [comment]
Another note: `free()` is always safe to use on `NULL`. We do rely on this in several cases, for example when freeing a `vector_ptr` when not all of its elements have been allocated yet (e.g. because we're aborting due to an error). This is why `igraph_Free` not only calls `free()` but also sets the pointer to `NULL`

**Comment by GroteGnoom** [comment]
Allright, I'll first fix #1479, and then revert a bit here.

**Review by ntamas — APPROVED** [review]

**Pull request merged**
