### PR TITLE
Smaller examples

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of https://github.com/igraph/igraph/issues/1574

### CODE REVIEW

**Comment by szhorvat** [comment]
@GroteGnoom @ntamas Can we get this into shape and merge before 0.10? I think there's great value in having good and educational examples.

**Comment by szhorvat** [comment]
I'll do a quick review right now to help with getting this ready.

A slight concern I have is that this duplicates a lot of the code, effectively creating many more tests than we had before. This will blow up the running time of the test suite.

Still, I think this approach of "forking" earlier examples into an example part and a test part will be a good approach for the long term.

**Comment by szhorvat** [comment]
@GroteGnoom Is there anything in particular that you'd want me to take a closer look in this PR?

**Comment by GroteGnoom** [comment]
At least 
[lapack_dgeevx](https://github.com/igraph/igraph/pull/2175/commits/552256da02032ea15514788c504d33e8c4f5b623) and
[lapack_dsyevr](https://github.com/igraph/igraph/pull/2175/commits/96cbda6aaac7993e59b6658d5eacce4d189e1df6)

**Comment by ntamas** [comment]
> Can we get this into shape and merge before 0.10?

It's not a tragedy if this does not get into 0.10 but only to 0.10.1 :) If you manage to mark this ready for review before I resume the 0.10 release process (not today, most likely tomorrow), it can get into 0.10. Otherwise it will get into 0.10.1. If you say that you need a bit more time to finish this (meaning a day or two, not a week or more), I am willing to wait a bit with 0.10.0, but as I said, one needs to draw a line somewhere, otherwise we could keep on delaying 0.10.0 indefinitely because there will always be "just one more thing" that we can squeeze into 0.10.0.

**Comment by szhorvat** [comment]
@GroteGnoom Can you merge develop into this and fix whatever is broken by the updated matrix printing?

Actually it's probably better to do what Tamás said and leave this for 0.10.1. It shouldn't block 0.10, and let's not give ourselves too much pressure.

**Review by szhorvat — APPROVED** [review]
I did not look at each test individually, but the general approach seems fine. If there are concerns about the lapack tests, can we leave them for later?

**Comment by szhorvat** [comment]
Just a note that after discussion in chat with @GroteGnoom, we decided that the `dgeevx` (and possibly `dsyevr`) example needs a bit more attention. Please do not merge until then.

**Comment by szhorvat** [comment]
`dsyevr` example looks good.

Nitpicks:

 - I think we don't need variables for `il`, `iu`, `vl, `vu`.
 - Docs could be explicit about what the "first" eigenvalue is (the largest, I presume)

**Comment by GroteGnoom** [comment]
> Optionally, the example can check the info value to see if we got convergence.
With an input of 1, errors are generated when there's a problem, so this check isn't necessary.

**Comment by GroteGnoom** [comment]
> Docs could be explicit about what the "first" eigenvalue is (the largest, I presume)

Yes, that would be nice. But I can't find it in the original docs either.

dsyevr:
https://netlib.org/lapack/explore-html/d2/d8a/group__double_s_yeigen_gaeed8a131adf56eaa2a9e5b1e0cce5718.html

dsyevr refers to dstemr:
https://netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga14daa3ac4e7b5d3712244f54ce40cc92.html

**Comment by GroteGnoom** [comment]
Now the dgeevx example does not show the general way to print out the eigenvectors, but to do it right we need something like arpack_unpack_complex.

**Comment by szhorvat** [comment]
> Now the dgeevx example does not show the general way to print out the eigenvectors, but to do it right we need something like arpack_unpack_complex.

Do you mean that you would like to introduce a function that converts the "compressed" representation that LAPACK returns into a proper complex matrix? Yes, that would be nice, but perhaps it's better to leave it for a followup PR, so this one can be merged. There are a very large number of files touched in this PR, so the risk of conflicts is high.

**Comment by GroteGnoom** [comment]
> Do you mean that you would like to introduce a function that converts the "compressed" representation that LAPACK returns into a proper complex matrix? Yes, that would be nice, but perhaps it's better to leave it for a followup PR, so this one can be merged. There are a very large number of files touched in this PR, so the risk of conflicts is high.

I agree, I want this merged as soon as possible.

**Comment by szhorvat** [comment]
> I agree, I want this merged as soon as possible.

Are you still planning to work on it, or is it good to go?

**Comment by szhorvat** [comment]
Great! Now if anyone has time to change all those `main()` to `main(void)` and remove https://github.com/igraph/igraph/blob/master/etc/cmake/compilers.cmake#L54 that would be great!

**Comment by szhorvat** [comment]
> Great! Now if anyone has time to change all those `main()` to `main(void)` in tests/examples and remove https://github.com/igraph/igraph/blob/master/etc/cmake/compilers.cmake#L54 that would be great!

This is done.

**Pull request merged**
