### PR TITLE
Triad census for undirected graphs

### LINKED ISSUE #872: triad_census returns bad output for undirected graph
For an undirected graph, `triad_census` returns a meaningless result and issues a warning.  This is true both for C and R.  The result is meaningless partly because some of it comes from uninitialized memory and partly because the assignment to MAN labels is inconsistent.  This situation is not ideal.  I propose one of the following solutions:

 - Turn the warning into an error instead, do not return a bad result.
 - Return zeros for triads containing asymmetric dyads, assign correctly to 300, 201, 102 and 003.  This would be consistent with `dyad_census`, which does return a meaningful result.

I can send a pull request, just let me know which solution you prefer.

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #872

### CODE REVIEW

**Comment by ntamas** [comment]
Can you add a few tests for `igraph_triad_census`, at least in the undirected case? (I know that we were being lazy and there are no tests for the directed case, but it is tested later on in the R and Python interfaces).

**Comment by szhorvat** [comment]
I don't really understand this testing framework, but I tried to add something.  Can you check it?

**Comment by szhorvat** [comment]
Also: I turned off igraph warnings in the test because I wasn't sure how to properly test for them.

**Comment by ntamas** [comment]
Seems good - I'll have a more detailed look at it tomorrow and then I'll merge it. Thanks!

**Comment by szhorvat** [comment]
Sorry about that, fixed now.

**Comment by ntamas** [comment]
Awesome, thanks a lot!

**Pull request merged**
