### PR TITLE
Check for int overflow in edge_betweenness

### PR DESCRIPTION
**Pull request by iosonofabio**
Addressing #51 

Problems found:
 - [x] `edge_betweenness`
 - [ ] `betweenness` is already using doubles... is that alright??
 - [x] `community_edge_betweenness`

There are no other instances of `unsigned long long int` or `unsigned long int` or `long long int` in the `src` folder, so I take it that these should be the only two obvious cases.

Is that fine that the `betweenness` is using doubles?

### CODE REVIEW

**Comment by vtraag** [comment]
Might it not be better to add an additional internal function like `igraph_i_add_int_safe` which does the overflow (and underflow) checks and raises an error? Otherwise the pattern needs to be repeated every time, inviting possible bugs. A macro instead of a function would also work of course.

**Comment by iosonofabio** [comment]
I'd be happy with that, a macro probably less problematic in terms of performance hit. Where do you think the macro could sit?

**Comment by vtraag** [comment]
Good question! I don't have any file in mind immediately, perhaps @ntamas has a suggestion. Perhaps we need a different header for this?

**Comment by szhorvat** [comment]
Testing tip:

Overflow in (edge or vertex) betweenness calculations should occur with a grid graph of size 35*35, but _not_ at size 34*35.

**Comment by szhorvat** [comment]
@iosonofabio In case you were still working on this: I tested out changing the `long long` to `double` and it does not seem to have any noticeable precision penalty while preventing overflow. It even makes the use of bigints unnecessary (though I don't want to remove bigint support as it was exactly that that allowed me to verify that `double`s work well). Details are in the chat.

Thus this check won't be necessary.

**Comment by iosonofabio** [comment]
Sounds good, thanks for that.

**Comment by szhorvat** [comment]
Closing in favour of #1576.

**Pull request closed without merging**
