### PR TITLE
community_leiden: fix crash when interrupting

### LINKED ISSUE #1368: Interruption of community_leiden crashes
When interrupting `community_leiden` this may result in crashing the Python session. Presumably it is a memory-related issue. I am not yet sure whether this is a problem of the Python interface or the C core. If it involves the latter I'll transfer the issue.

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #1368

### CODE REVIEW

**Comment by szhorvat** [comment]
@ntamas Do you know why the Travis checks went missing? Also, AppVeyor issue doesn't seem to want to go away.

**Comment by vtraag** [comment]
I see I left some other functions (at least the quality function) also without a proper `IGRAPH_CHECK`, which should also still be corrected. I can't correct it right now, but I'll take a look when I get around to it.

**Comment by szhorvat** [comment]
@vtraag Perhaps it's easiest to just push to this PR?

**Comment by vtraag** [comment]
Yes, I'll push to this PR when I get around to it.

**Comment by ntamas** [comment]
> Do you know why the Travis checks went missing?
I have no idea; Travis itself was correctly executed on this PR (see [this link](https://travis-ci.org/github/igraph/igraph/builds/673724009/), but it did not appear above in the CI summary for some reason. I'll try to figure this out.

> Also, AppVeyor issue doesn't seem to want to go away.
I'll try to sort this out; stay tuned.

**Comment by ntamas** [comment]
Appveyor seems to work again now; the fix is in the `develop` branch so feel free to merge it back into this PR.

**Comment by ntamas** [comment]
Looks like the Travis checks also came back, although I have no idea what could have caused this.

**Comment by szhorvat** [comment]
If there are no comments/concerns, I'll merge this in a few hours.

**Comment by szhorvat** [comment]
@vtraag @ntamas  OK, it's merged but I've forgotten about the two branches now. Should I simply merge it also into `develop`? Or cherry pick just the relevant part and add that to `develop`?

**Comment by vtraag** [comment]
I've just merged the `fixed/issue-1368` branch to the `develop` branch, thanks for taking note @szhorvat .

**Pull request merged**
