### PR TITLE
cmake: disable uninteresting MSVC warnings

### PR DESCRIPTION
**Pull request by szhorvat**
This disables some uninteresting warnings from MSVC. See #1507

### CODE REVIEW

**Comment by szhorvat** [comment]
The MS compiler output should be less overwhelming now, and we should be able to see relevant warnings more easily:

https://ci.appveyor.com/project/ntamas/igraph/builds/36240213

**Comment by szhorvat** [comment]
The MSVC output should hopefully be less chaotic, see here when build has finished: https://ci.appveyor.com/project/ntamas/igraph/builds/36240321

**Comment by vtraag** [comment]
Sorry, I didn't get around to replying to your comment https://github.com/igraph/igraph/issues/1507#issuecomment-724746757 anymore. I'm perfectly fine with the (silence) warning flags that you put in here now.

I do want to raise the point that I think we should address error `warning C4456: declaration of variable hides previous local declaration`. This can point out potential issues with new code, and I therefore think that it would be nice if we can enable this warning again.

Finally, after we have silenced/fixed all warning, we should then enable error on warnings (`/WX`). That way, any new contributions get verified well.

**Comment by ntamas** [comment]
The MSVC build output looks much better now.

How about this: we address the warnings that we think need to be addressed, based on the current CI output, and push changes to this branch until we get close to zero warnings. Then we re-enable C4456 as proposed by @vtraag, do another iteration until we are happy with the output, and then merge this PR. Basically this PR would be the clean-up-the-warnings-in-MSVC branch.

**Comment by vtraag** [comment]
It might be better to merge this PR first and open separate PRs for separate warnings. The previous issues were also addressed in separate PRs as well (#1531, #1532, #1536), which might be needed, as we first discussed in PR #1530.

**Comment by ntamas** [comment]
Okay, let's merge and continue in separate PRs.

**Pull request merged**
