### PR TITLE
feat: Floyd-Warshall shortest paths

### PR DESCRIPTION
**Pull request by szhorvat**
### Changes

 - Floyd-Warshall shortest path algorithm for very dense graphs
 - Fix roundoff errors creating negative weights in the reweighting process of the Johnson shortest path algorithm
 - Benchmark for graph distance calculations
 - Update printing of empty matrices in tests. If the row or column count is zero, they are now printed as `[ nrow-by-ncol ]` so we can test for the correctness of sizes. For example, 2D layout algorithms should return a 2-by-0 matrix, not a 0-by-0 ones, for the null graph.

### Questions

 - Can we rely on the fact that `IGRAPH_ALL == IGRAPH_IN | IGRAPH_OUT` and simply test `mode & IGRAPH_OUT` to determine if a certain direction should be considered? This is used within `type_indexededgelist.c` and is sometimes very convenient.
 - @ntamas Let me know what argument ordering you prefer between `mode` and `weights`.

### CODE REVIEW

**Comment by GroteGnoom** [comment]
Since there's a new and improved matrix_print now, should we also try to use that as much as possible in tests? And then remove the special test function altogether?

**Comment by szhorvat** [comment]
It would indeed be nice to have adaptive column width from the new `igraph_matrix_print()`. But I'm not keen on losing the feature that clearly marks the beginning and end of the matrix.

The original reason I added `vector_print()` with the `( ... )` style was to be able to see empty vectors. Then came the matrix version with `[ ... ]`. What this provides is:

 - Clearly show empty vectors/matrices
 - Indicate where a matrix starts and ends in case multiple matrices are printed one after the other. This was an annoyance in older versions of tests.
 - Clearly differentiate vectors (or a series of vectors) from matrices

Of course when you're writing the test, these are not usually a big deal. But when a test suddenly fails and I have no idea why, it helps to be able to interpret the output even before I could look at the sources.

It would be good to think about a solution that preserves these benefits as well.

**Comment by szhorvat** [comment]
I marked this as draft now as I added a benchmark which revealed an issue in the Johnson algorithm, which I want to fix as well.

**Comment by szhorvat** [comment]
Benchmark results:

```

|> Benchmark file: /Users/szhorvat/Repos/igraph-main/igraph/tests/benchmarks/igraph_distances.c
|  1 vcount=100, p=0.5, Unweighted, 200x                                           0.096s  0.096s      0s
|  2 vcount=100, p=0.5, Dijkstra, 200x                                             0.765s  0.764s      0s
|  3 vcount=100, p=0.5, Unweighted Floyd-Warshall, 200x                            0.242s  0.242s      0s
|  4 vcount=100, p=0.5, Floyd-Warshall, 200x                                       0.348s  0.347s      0s
|  5 vcount=100, p=0.5, Bellman-Ford (negative), 200x                              0.778s  0.777s      0s
|  6 vcount=100, p=0.5, Johnson (negative), 200x                                   0.848s  0.847s  0.001s
|  7 vcount=100, p=0.5, Floyd-Warshall (negative), 200x                            0.358s  0.358s      0s

|  1 vcount=500, p=0.1, Unweighted, 10x                                            0.132s  0.131s      0s
|  2 vcount=500, p=0.1, Dijkstra, 10x                                               1.23s   1.23s      0s
|  3 vcount=500, p=0.1, Unweighted Floyd-Warshall, 10x                              1.36s   1.36s      0s
|  4 vcount=500, p=0.1, Floyd-Warshall, 10x                                         1.54s   1.54s      0s
|  5 vcount=500, p=0.1, Bellman-Ford (negative), 10x                                1.57s   1.57s      0s
|  6 vcount=500, p=0.1, Johnson (negative), 10x                                     1.26s   1.25s  0.001s
|  7 vcount=500, p=0.1, Floyd-Warshall (negative), 10x                              1.56s   1.56s      0s

|  1 vcount=1500, p=0.02, Unweighted, 1x                                           0.118s  0.115s  0.003s
|  2 vcount=1500, p=0.02, Dijkstra, 1x                                             0.862s  0.861s      0s
|  3 vcount=1500, p=0.02, Unweighted Floyd-Warshall, 1x                             4.12s   4.12s  0.002s
|  4 vcount=1500, p=0.02, Floyd-Warshall, 1x                                        4.31s   4.31s  0.001s
|  5 vcount=1500, p=0.02, Bellman-Ford (negative), 1x                                1.8s    1.8s  0.001s
|  6 vcount=1500, p=0.02, Johnson (negative), 1x                                   0.895s  0.893s  0.001s
|  7 vcount=1500, p=0.02, Floyd-Warshall (negative), 1x                             4.67s   4.66s  0.003s
```

**Comment by szhorvat** [comment]
Marked as "experimental" so that if #2197 gets implemented, the various types of speedups could be integrated into this function and selected with a "method" parameter.

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
whoops, sorry

**Pull request merged**
