### PR TITLE
CI: Use clang15.

### PR DESCRIPTION
**Pull request by vtraag**
This is an attempt at addressing issue #2236.

### CODE REVIEW

**Comment by vtraag** [comment]
It seems that this now correctly uses `clang-15` instead of `clang-14`. Perhaps you still want to change something else @szhorvat, with regards to ASan or something else?

**Comment by ntamas** [comment]
Looks fine to me!

**Comment by szhorvat** [comment]
This looks good to me. As I understand, it's not cached, but I think that's too much to ask anyway.

**Review by szhorvat — APPROVED** [review]

**Comment by vtraag** [comment]
It seems that the build also passes, so that is great. We can also test with `clang-16` by the way, but that is probably not really necessary.

**Comment by szhorvat** [comment]
No, let's not test with unreleased versions. It's not necessary. Clang 15 was important because people (and CRAN) complained already.

**Comment by vtraag** [comment]
> it's not cached, but I think that's too much to ask anyway.

No, it's not indeed. But the setup only takes 24s in total, so I thought it wasn't worth the trouble anyway.

**Comment by szhorvat** [comment]
I don't mind if it takes 3 minutes.

I was just never sure if we were supposed to be good citizens and keep bandwidth usage low. But given how GitHub actions are typically used, they probably don't care.

**Pull request merged**
