### PR TITLE
Add dyad_census unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of #1592

### CODE REVIEW

**Comment by szhorvat** [comment]
This is a fix that would be nice to have on `master`. It relies on `igraph_i_neighbors`, which is only on `develop`. Do we want to backport that function to `master` @ntamas ?

**Comment by ntamas** [comment]
Since it's internal, provides no visible changes in the public API, and it is well-tested, I'm totally fine with backporting it. I can do it later this evening, or feel free to go ahead (just let me know so we don't duplicate work).

**Comment by szhorvat** [comment]
I won't touch it today.

**Comment by ntamas** [comment]
There was a hiccup while rebasing this PR against `master`; Github seems to have merged the entire `develop` branch back into `master` instead. I'll fix this manually on the `master` branch.

**Comment by ntamas** [comment]
All clear now.

**Comment by szhorvat** [comment]
Something's wrong, for a 2-vertex graph I always get `Integer overflow, returning -1`

image

**Comment by szhorvat** [comment]
This should fix it, c505cbaca56e674db8645e454e280b081f4e73a2

**Pull request merged**
