### PR TITLE
New feature: maximum matching of general graph

### PR DESCRIPTION
**Pull request by EdgarAlenPoe**
Implementing the blossom algorithm for finding maximum cardinality matchings in non-bipartite graphs.
As per issue [#2403](https://github.com/igraph/igraph/issues/2403)

### CODE REVIEW

**Comment by ntamas** [comment]
There's an invalid read in the `igraph_maximum_matching` test case according to AddressSanitizer:

```
==17484==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000002d0f at pc 0x555f57535bdf bp 0x7ffecbcb2560 sp 0x7ffecbcb2550
READ of size 1 at 0x602000002d0f thread T0
    #0 0x555f57535bde in igraph_i_maximum_matching_find_aug_path /home/vsts/work/1/s/src/misc/matching.c:1464
    #1 0x555f575362cc in igraph_maximum_matching_unweighted /home/vsts/work/1/s/src/misc/matching.c:1130
    #2 0x555f5753a67a in igraph_maximum_matching /home/vsts/work/1/s/src/misc/matching.c:1083
    #3 0x555f574bc61b in test_general_graphs /home/vsts/work/1/s/tests/unit/igraph_maximum_matching.c:117
    #4 0x555f574bcbc1 in main /home/vsts/work/1/s/tests/unit/igraph_maximum_matching.c:157
    #5 0x7f6416429d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #6 0x7f6416429e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #7 0x555f574b8bc4 in _start (/home/vsts/work/1/s/build/tests/test_igraph_maximum_matching+0x22bc4)

0x602000002d0f is located 1 bytes to the left of 11-byte region [0x602000002d10,0x602000002d1b)
allocated by thread T0 here:
    #0 0x7f6416eb4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x555f574e1234 in igraph_vector_bool_init /home/vsts/work/1/s/src/core/vector.pmt:144
    #2 0x555f5753468c in igraph_i_maximum_matching_find_aug_path /home/vsts/work/1/s/src/misc/matching.c:1196
    #3 0x555f575362cc in igraph_maximum_matching_unweighted /home/vsts/work/1/s/src/misc/matching.c:1130
    #4 0x555f5753a67a in igraph_maximum_matching /home/vsts/work/1/s/src/misc/matching.c:1083
    #5 0x555f574bc61b in test_general_graphs /home/vsts/work/1/s/tests/unit/igraph_maximum_matching.c:117
    #6 0x555f574bcbc1 in main /home/vsts/work/1/s/tests/unit/igraph_maximum_matching.c:157
    #7 0x7f6416429d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```

The graph also needs to be freed in `examples/simple/igraph_maximum_matching.c` to prevent memory leak warnings in CI tests.

**Comment by szhorvat** [comment]
Is this PR ready for review?  I suppose yes, since you were asking about starting work on other issues.

It'll be a little while before reviewing this, since the Easter holidays are coming up, and many of us will be offline for a while.

**Comment by szhorvat** [comment]
In the meantime, would you be able to reformat the newly added source file with astyle? Use `.astylerc` from the repo's root directory.

If you are not sure how to do this, let me know, and I'll push a commit with the reformatting.

**Comment by EdgarAlenPoe** [comment]
Yes it's ready for review, sorry for any confusion.

It'd probably be best if you did the reformatting.

**Comment by szhorvat** [comment]
Oops ... that was not intentional.

**Comment by ntamas** [comment]
> Oops ... that was not intentional.

Shall we force-push to the commit preceding it and restart the review?

**Comment by szhorvat** [comment]
I fixed our `develop` by force pushing to just before merging this PR. But I can't reopen the PR.  Since the mistake I made is related to @EdgarAlenPoe's branch also being called `develop`, it'd be easier to start a new PR from a new branch. It shouldn't take more than a minute or to to open the new PR ...

**Comment by EdgarAlenPoe** [comment]
Yeah, sorry, I realized I should have named it something else after I'd opened the pull request. I'll have that pull request ready in just a minute.

**Pull request merged**
