### PR TITLE
Correct numerical issues in SIR

### LINKED ISSUE #620: SIR failure
By changing the time scale of the two rates in sir I get a failure 

> set.seed(42);sirres6 <- sir(HGeg4agc,beta=6, gamma=10, 100)
> set.seed(42);sirresp6 <- sir(HGeg4agc,beta=.6, gamma=1, 100)
> Error in sir(HGeg4agc, beta = 0.6, gamma = 1, 100) : 
>   At sir.c:178 : Internal SIR error, Internal error, likely a bug in igraph
> 
> HGeg4agc
> IGRAPH U--- 610 1469 -- 
> is.simple(HGeg4agc)
> [1] TRUE

I can e-mail the graph as an RData file or dput it  here.

### PR DESCRIPTION
**Pull request by vtraag**
This seems to fix #620. The problem was that some nodes were still being sampled, while there were no nodes actually left to be sampled.

### CODE REVIEW

**Comment by vtraag** [comment]
It seems that the AppVeyor build was canceled because I pushed a new commit while it was running, but it didn't get restarted. I can't seem to restart the AppVeyor build, perhaps I don't have sufficient rights (I logged in using my GitHub credentials). Perhaps you can restart it @ntamas ?

**Comment by ntamas** [comment]
Restarted the build; fingers crossed.

**Comment by vtraag** [comment]
I believe this should now be good to go?

**Comment by ntamas** [comment]
Aaaah, I screwed it up. I accidentally squashed instead of rebasing, and then I tried to revert the PR... can you send it once again please so I could merge it again?

**Comment by vtraag** [comment]
OK, created a new PR #1210.

**Comment by vtraag** [comment]
Next time, I'll properly rebase before pushing :)

**Pull request merged**
