### PR TITLE
Addressing #718: decompose into strongly connected components

### PR DESCRIPTION
**Pull request by iosonofabio**
DO NOT MERGE YET!

Implemented as a mix of `igraph_decompose` (now `igraph_decompose_weak`) and `igraph_clusters_strong`.

I need to add tests, but wanted to put it out there for you to review if you have a minute.

This addresses #718 
Thanks

### CODE REVIEW

**Comment by iosonofabio** [comment]
I added tests for this, should be good to go, let's just wait for CI

**Comment by szhorvat** [comment]
Normally, functions that are no part of the public API are named `igraph_i_` and are marked as local to the compilation unit (`static`). I wonder why `igraph_clusters_weak` and `igraph_clusters_strong` were not like this. I saw that you modelled `igraph_decompose_(strong|weak)` after these.

**Comment by iosonofabio** [comment]
I'm happy to rename them for consistency. If it's not part of the API, it should be fine.

**Comment by ntamas** [comment]
> I wonder why igraph_clusters_weak and igraph_clusters_strong were not like this.
Historical reasons :) (igraph has a looooong history). Feel free to rename these and `igraph_decompose_(strong|weak)` as well.

**Comment by szhorvat** [comment]
Just to make this explicit then, the declaration should be

```c
static int igraph_i_clusters_weak(...);
```

with the arguments filled in for `...`, of course :)

> igraph has a looooong history

We're working on it _because_ it has a long enough history that it accumulated more useful functionality than most alternatives :)

**Comment by iosonofabio** [comment]
done, passes tests locally, let's see on CI :-)

**Comment by ntamas** [comment]
Seems good to me, thanks!

**Pull request merged**
