### PR TITLE
Draft changelog for 0.8

### PR DESCRIPTION
**Pull request by szhorvat**
This is a draft changelog for 0.8.

Feel free to edit (edits from maintainers are enabled in this PR).

### CODE REVIEW

**Comment by szhorvat** [comment]
I just noticed that the `ChangeLog` file I renamed to `CHANGELOG.md` had this commit note:

> Readded (empty) ChangeLog file, needed for automake.

Despite that, `,/configure` gave me no complaints. Does anyone remember why `ChangeLog` was needed? Should I re-add an empty one or rename `CHANGELOG.md` back?

**Comment by vtraag** [comment]
I've compare the `include` directory with the `0.7.1` version, and added some additional changes I noticed. Regarding the need of `ChangeLog`, I don't know, sorry.

**Comment by ntamas** [comment]
`ChangeLog` is mandated by the GNU coding standards, so `automake` complains if you don't have one. (It probably does not fail the build, though). Even the format of the `ChangeLog` file is strictly specified so you cannot symlink a generic Markdown file as `ChangeLog` to fool `automake`. *sigh*

**Comment by szhorvat** [comment]
> `ChangeLog` is mandated by the GNU coding standards

Do we care about GNU standards?

Should I leave it as is (markdown is nice!) or reformat to GNU standards? I *roughly* followed https://keepachangelog.com/ combined with a bit of common sense to improve readability.

**Comment by vtraag** [comment]
Note that I didn't follow a chronological order per se.

**Comment by szhorvat** [comment]
`igraph_solve_lsap()` is not documented. I never knew if it was ready and tested. I believe it was added to eventually replace the R implementation of graph matching. 

If we include it in the changelog, we should add documentation.

@gaborcsardi, do you know what status of this function is? Ready to use?

**Comment by gaborcsardi** [comment]
> @gaborcsardi, do you know what status of this function is? Ready to use?

IDK, just ignore it, I would say.

**Comment by szhorvat** [comment]
Removed `igraph_solve_lsap` from the changelog per Gábor's comment. We can test it later and perhaps make it public in 0.9

**Comment by ntamas** [comment]
> Do we care about GNU standards?

I guess not so much any more, at least compared to how much we used to care about them several years ago :) I'd prefer to have the changelog in Markdown as well - Github formats it nicely, and later on we could even switch to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/), which would allow us to generate changelogs from the commit messages instead of writing them manually. However, in order to silence `automake` for the time being, we should have a regular `ChangeLog` file that just points the user to the "real" changelog. We can remove it once we switch the build system from Autotools to CMake in the future.

**Comment by szhorvat** [comment]
Re-added `ChangeLog` file and kept `CHANGELOG.md` as-is.

Please everyone have a read-though of the changelog. If there are no concerns by the end of the day, we should merge this.

**Comment by ntamas** [comment]
Seems OK to me so far! I'll merge around 10pm CET if there are no objections.

**Comment by szhorvat** [comment]
I just noticed that there's already a `NEWS` file with changes up to 0.6.5 but not 0.7. What do we do with that? Transfer its contents?

Unrelated: There is also an ancient `TODO` file which should probably be removed.

**Comment by ntamas** [comment]
Both of these are obsolete and can be removed. The NEWS file was also mandated by the GNU coding standards, so we should probably keep a placeholder in it. 

T.

**Comment by ntamas** [comment]
Old news file renamed from `NEWS` to `ONEWS` (as suggested by the GNU coding standards). We can remove this file in 0.9 or so. Added new `NEWS` file that simply refers the user to `CHANGELOG.md`. These are already in master.

**Pull request merged**
