### PR TITLE
Cycle basis calculations

### LINKED ISSUE #1252: Wishlist: Cycle basis of undirected graph
This is a suggestion to implement finding a [cycle basis](https://en.wikipedia.org/wiki/Cycle_basis) of an undirected graph. Additionally, implement finding a minimum weight cycle basis (see also [Horton bases](https://en.wikipedia.org/wiki/Cycle_basis#Polynomial_time_algorithms)).

Consider extensions to directed graphs later.

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #1252

### CODE REVIEW

**Comment by szhorvat** [comment]
I am still working on this.

**Comment by ntamas** [comment]
This PR should eventually be updated to use `igraph_vector_int_list_t` to return cycles; I'm not touching this at the moment as it's still a draft and Github won't let me check for merge conflicts until I mark this as ready for review.

**Comment by szhorvat** [comment]
It's okay, I'll deal with this one.

**Comment by szhorvat** [comment]
Closing in favour of #1957

**Pull request closed without merging**
