### PR TITLE
add igraph_get_shortest_paths_bellman_ford;

### PR DESCRIPTION
**Pull request by pyrovski**
This code will compute shortest paths for graphs with negative edge weights.
Merging this will resolve [issue #632](https://github.com/igraph/igraph/issues/632), at least in the C library. I will also create a pull request for the R interface.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks, I'll look over it, probably in 1-2 weeks on so only, sorry about the delay.

**Comment by ntamas** [comment]
I took a quick look at it and it seems to be okay; we will need test cases for `igraph_get_shortest_paths_bellman_ford`, though.

**Comment by pyrovski** [comment]
I renamed the getPath function, and will work on adding tests.

**Comment by dHannasch** [comment]
Hi,
I know I'm late to the party here, but I'm working on a igraph_dag_single_source_longest_paths that should take advantage of a topological ordering to find longest paths in O( s(|V| + |E|) ).
I have a question. igraph_topological_sorting gives out the result as a igraph_vector_t, a vector of floating-point numbers, rather than a igraph_vector_long_t.
Yet, in the code of igraph_topological_sorting, it only ever places longs in the result vector.
Is this just a legacy from a previous version where you used various nonintegers as error codes or somesuch, or is there a reason for this?
I am planning to have an (optional) igraph_vector_long_t* predecessors to allow tracing back the longest paths if desired; should this be a igraph_vector_t* instead?

Thank you,
David Hannasch

**Comment by ntamas** [comment]
`igraph_topological_sorting` uses an `igraph_vector_t` because it was added way before we have implemented `igraph_vector_long_t` (or any other non-floating-point vector type). So yes, it is just a legacy feature, but non-integers were never used as error codes in igraph so you can be sure that the result vector will always contain integers only (despite the type of each element being a floating-point number). Feel free to use `igraph_vector_t` or `igraph_vector_long_t` in your code for the predecessor vector, whichever is more convenient to you.

**Comment by gaborcsardi** [comment]
What's the status of this? Can I look at it, or is somebody working on it?

**Comment by ntamas** [comment]
I haven't been looking at it for a while so feel free to go ahead.

**Comment by gaborcsardi** [comment]
Yeah, what I meant, is that there are still no tests, so I guess it is not ready to merge. Anyway, I'll close it now, and please feel free to reopen/resubmit this when you think it is ready.

**Comment by wlandau** [comment]
Any update on this feature? I was really hoping to find a shortest or longest path algorithm in `igraph`.

**Comment by szhorvat** [comment]
igraph already has many shortest path related functions:

http://igraph.org/c/doc/igraph-Structural.html#idm470927281168

What do you need specifically that is not already available?

**Comment by wlandau** [comment]
That's great to hear, thanks for the link. I will check it out.

**Comment by szhorvat** [comment]
I think I misunderstood. It seems that the existing functions can calculate the path *length* even with negative weights (which you can use for longest paths), but they cannot calculate the actual path.

**Pull request closed without merging**
