### PR TITLE
degree_sequence_game: add uniform sampling

### LINKED ISSUE #1091: igraph_set_contains is buggy
`igraph_set_contains` is broken when used on empty sets.

https://github.com/igraph/igraph/blob/02005680aebb4281f2964c6d2d8d98851fce63b9/src/igraph_set.c#L257

It has `right = igraph_set_size(set)-1;`. If the set is empty, then `right == -1`. Despite this, it uses `right` for indexing (out-of-bounds error).

In my situation this led to `igraph_set_contains` claiming that an empty set contains `0`. 

What is the status of the `igraph_set_t` functions?  Are they safe to use?  They seem to get very limited use at the moment.

### PR DESCRIPTION
**Pull request by szhorvat**
This PR is another one back from April that I did not send in. It adds uniform sampling for *simple* graphs to `degree_sequence_game` based on the configuration model. Please do review the code before merging.

Related: #1089 

Related: #1072 

It also fixes #1091

### CODE REVIEW

**Comment by szhorvat** [comment]
Details:

Currently in `degree_sequence_game` we have:

`IGRAPH_DEGSEQ_SIMPLE`, which generates multigraphs.  Here, the documentation is improved, explaining that this is the configuration model, and providing specific details on sampling probabilities.

There is one point that I notice I did not write down: the probabilities are given in terms of the adjacency matrix. For undirected graphs, this is the kind of adjacency matrix that has a 2 (not a 1) on the diagonal for loop edges.  There are two conventions about loop edges and adjacency matrices: put a 1 in the adjacency matrix (because there is one loop edge) or put a 2 (because both ends of that loop edge connect to the relevant vertex). Maybe I should not this explicitly.

`IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE`, which does not generate multigraphs, but does not sample uniformly either.

This PR adds another method, which does sample uniformly.

There is also `IGRAPH_DEGSEQ_VL`, but that is a very different method that generates only connected graphs, and does not sample *exactly* uniformly.

----

About the naming of enum value:

I find the current naming confusing because the method that does generate multigraphs is called "SIMPLE". I did not rename them because that would break compatibility, and it seemed like a minor thing.  Users of the C interface should read the documentation carefully. Renaming can be done in the high-level interfaces, if deemed necessary.

**Comment by ntamas** [comment]
Please let me know whether you'd like to try implementing the check-for-loop-edges-first idea outlined above; if not, I might try it on my own after this one is merged.

**Comment by szhorvat** [comment]
Sorry for the late response ... I will be away for a while, then work will be busy. So I might not work on this at all until late January.  Feel free to implement this!  I will let you know when I come back to this, so we don't duplicate work.

**Comment by ntamas** [comment]
Okay, I've merged the PR for the time being and we can return to this later as time allows.

**Comment by szhorvat** [comment]
> Please let me know whether you'd like to try implementing the check-for-loop-edges-first idea outlined above; if not, I might try it on my own after this one is merged.

If you have not yet done this, I'll do it around next weekend. Let me know.

**Comment by szhorvat** [comment]
Note to self: 

Another improvement that could be made: if the graph is dense (> 50%), then generate the complement instead, then convert it back to the desired graph. The configuration model's algorithm will fail on even tiny almost-complete graphs.

Counter-argument for doing this: we may not be able to judge in the best way when it is worth complementing the sequence. Thus doing this is better left to the user than trying to make our algorithm too smart.

@ntamas  What do you think?

**Comment by ntamas** [comment]
I would resist the tempation to guess; just document the caveat and then let the user try it if needed.

**Pull request merged**
