### PR TITLE
Add benchmark for using lazy adjlist in neighborhood

### PR DESCRIPTION
**Pull request by GroteGnoom**
Because of #1954

We want to consider using a lazy_adjlist for igraph_neighborhood.
If it turns out that's a wise idea, we might not want to merge the benchmarks at
all but just replace the old igraph_neighborhood. The benchmarks are
here just to make a decision.

The full graph and ring graph are there to show some extreme cases, so it's clear neither method is always faster.

I've also put together a different lazy adjlist, just to see how much quicker it would be than the usual lazy adjlist. It completely breaks encapsulation, but I thought it would be important to at least see what the tradeoffs were. If it's good enough, maybe we can make it cleaner, and still keep the benefits?

Todo:
use malloc instead of calloc for data in lazy adjlist 2
maybe try to optimize the non-lazy adjlist too?

Results for all vertices (on one particular computer):
```
Select all vertices:

Full graph:
order 1:
| Original function:                                                               0.017s  0.015s  0.001s
| Using a lazy adjlist:                                                            0.023s  0.021s  0.003s
| Using lazy adjlist 2:                                                            0.015s  0.015s      0s
| Using adjlist:                                                                   0.018s  0.018s      0s
order 2:
| Original function:                                                                1.76s   1.76s  0.002s
| Using a lazy adjlist:                                                             1.15s   1.14s  0.002s
| Using lazy adjlist 2:                                                              1.1s    1.1s  0.001s
| Using adjlist:                                                                    1.12s   1.11s  0.002s
order 3:
| Original function:                                                                1.78s   1.77s  0.002s
| Using a lazy adjlist:                                                             1.12s   1.11s  0.001s
| Using lazy adjlist 2:                                                             1.45s   1.45s  0.001s
| Using adjlist:                                                                   0.806s  0.804s  0.001s

Ring graph:
order 1:
| Original function:                                                               0.351s  0.345s  0.006s
| Using a lazy adjlist:                                                             1.02s  0.983s  0.032s
| Using lazy adjlist 2:                                                            0.379s  0.372s  0.006s
| Using adjlist:                                                                    0.65s   0.64s  0.008s
order 2:
| Original function:                                                               0.491s  0.483s  0.008s
| Using a lazy adjlist:                                                             1.16s   1.14s  0.022s
| Using lazy adjlist 2:                                                            0.475s  0.469s  0.006s
| Using adjlist:                                                                   0.723s   0.71s  0.012s
order 3:
| Original function:                                                               0.645s   0.63s  0.014s
| Using a lazy adjlist:                                                             1.19s   1.15s  0.035s
| Using lazy adjlist 2:                                                            0.547s   0.53s  0.016s
| Using adjlist:                                                                   0.807s  0.784s  0.021s

Random graph:
order 1:
| Original function:                                                               0.008s  0.008s      0s
| Using a lazy adjlist:                                                             0.02s  0.019s      0s
| Using lazy adjlist 2:                                                            0.009s  0.009s      0s
| Using adjlist:                                                                   0.013s  0.013s      0s
order 2:
| Original function:                                                               0.125s  0.124s  0.001s
| Using a lazy adjlist:                                                            0.114s  0.111s  0.003s
| Using lazy adjlist 2:                                                            0.098s  0.096s  0.002s
| Using adjlist:                                                                   0.099s  0.098s      0s
order 3:
| Original function:                                                                1.84s   1.79s   0.04s
| Using a lazy adjlist:                                                             1.34s   1.29s  0.042s
| Using lazy adjlist 2:                                                             1.33s   1.29s  0.046s
| Using adjlist:                                                                    1.27s   1.24s  0.022s


Select 10% of vertices:

Full graph:
order 1:
| Original function:                                                               0.012s  0.012s      0s
| Using a lazy adjlist:                                                            0.016s  0.016s  0.001s
| Using lazy adjlist 2:                                                            0.017s  0.016s      0s
| Using adjlist:                                                                   0.062s  0.062s      0s
order 2:
| Original function:                                                                1.84s   1.84s  0.002s
| Using a lazy adjlist:                                                             1.19s   1.19s  0.001s
| Using lazy adjlist 2:                                                             1.17s   1.17s  0.002s
| Using adjlist:                                                                    1.19s   1.19s  0.001s
order 3:
| Original function:                                                                1.81s    1.8s  0.002s
| Using a lazy adjlist:                                                             1.22s   1.22s  0.002s
| Using lazy adjlist 2:                                                             1.52s   1.52s  0.002s
| Using adjlist:                                                                   0.892s   0.89s  0.001s

Ring graph:
order 1:
| Original function:                                                               0.338s  0.337s      0s
| Using a lazy adjlist:                                                            0.897s  0.894s  0.001s
| Using lazy adjlist 2:                                                            0.363s  0.361s  0.001s
| Using adjlist:                                                                    3.15s   3.14s  0.011s
order 2:
| Original function:                                                               0.453s  0.451s  0.001s
| Using a lazy adjlist:                                                            0.981s  0.979s  0.001s
| Using lazy adjlist 2:                                                            0.431s   0.43s  0.001s
| Using adjlist:                                                                    3.28s   3.25s  0.024s
order 3:
| Original function:                                                               0.587s  0.585s  0.001s
| Using a lazy adjlist:                                                             1.03s   1.03s  0.001s
| Using lazy adjlist 2:                                                            0.519s  0.517s  0.002s
| Using adjlist:                                                                    3.31s   3.28s  0.021s

Random graph:
order 1:
| Original function:                                                               0.008s  0.008s      0s
| Using a lazy adjlist:                                                             0.02s   0.02s      0s
| Using lazy adjlist 2:                                                             0.01s   0.01s      0s
| Using adjlist:                                                                   0.066s  0.066s      0s
order 2:
| Original function:                                                               0.124s  0.124s      0s
| Using a lazy adjlist:                                                            0.204s  0.203s      0s
| Using lazy adjlist 2:                                                             0.11s   0.11s      0s
| Using adjlist:                                                                   0.149s  0.148s      0s
order 3:
| Original function:                                                                1.82s   1.81s  0.002s
| Using a lazy adjlist:                                                             1.42s   1.41s  0.002s
| Using lazy adjlist 2:                                                             1.29s   1.29s  0.002s
| Using adjlist:                                                                    1.32s   1.31s  0.002s

```

### CODE REVIEW

**Comment by szhorvat** [comment]
There is no doubt that using either a lazy or non-lazy adjlist will speed this up if: (1) using an order greater than 1 (2) computing it for all vertices.

The question is: Will there be a noticeable slowdown when computing it only for some of the vertices with a small order (or order=1)?  Making the adjlist lazy should prevent any slowdown.

I noticed that you used a complete graph for the benchmark. In most cases, such a graph is not representative of real use cases. In this case, in particular, a complete graph does not make much sense as 1st order of each vertex is already the entire graph. 

A random graph (Erdős-Rényi) would be a good starting point, but when processing only some vertices or just a single one (instead of all) you need to be careful not to accidentally start at one which is in a tiny component, or even a single isolated vertex. It will have a very small neighbourhood. You could keep generating random graphs until you get a connected one. To get a reasonable probability that the graph is connected, make sure that it has at least `n log(n) / 2` edges where `n` is the vertex count.

**Comment by szhorvat** [comment]
Now that's surprising to me:

```
Ring graph:
order 1:
| Original function:                                                               0.025s  0.024s  0.001s
| Using adjlist:                                                                   0.063s  0.059s  0.004s
```

Is this consistently reproducible? What if you add a `REPEAT` in there to bring the timing closer to 1 second (and therefore make it more reliable)?

**Comment by GroteGnoom** [comment]
I thought this would happen because of lots of little mallocs. I'll try to get some profiling going later 🙂

**Comment by szhorvat** [comment]
I would merge this before 0.10, just so that we don't have a PR that keeps getting out of sync with the main branch. Can you bring this up to date with `develop` @GroteGnoom and make sure it still compiles?

**Comment by ntamas** [comment]
Merged `develop` into this and updated the code so it compiles and runs again.

**Comment by ntamas** [comment]
I'm going to merge this into `develop` tomorrow before the scheduled 0.10.0 release unless there are objections. Shout if you don't want this :)

**Comment by szhorvat** [comment]
> before the scheduled 0.10.0 release

As I said before, I strongly suggest not to release 0.10 until py-igraph 0.10 is also ready, and can be released at the same time or the latest on the next day.

**Pull request merged**
