### PR TITLE
Add sparsemat_nonzero_storage unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of #1592

Also added some documentation.

Biggest change: Documentation with one space missing in doxrox were
                silently ignored. Fixed the spaces, not the silent
                ignoring.

### CODE REVIEW

**Comment by szhorvat** [comment]
It is unfortunate that `igraph_sparsemat_nonzero_storage`, `igraph_sparsemat_nzmax`, `igraph_sparsemat_iterator_row`, `igraph_sparsemat_iterator_col`, `igraph_sparsemat_iterator_next`, `igraph_sparsemat_iterator_idx` return an `int`. When I see `int`, I assume error code. 

I would like to cautiously suggest making these return an `igraph_integer_t` for clarity. Currently an `igraph_integer_t` is an `int`, so this would not break API and we can have it in 0.9.1. It would be a cosmetic change for now.

If in the future we change `igraph_integer_t`, CXSparse has the flexibility to adapt (it comes with several versions, some of which use longer values).

@ntamas Any objections to making these functions return `igraph_integer_t`?

**Comment by GroteGnoom** [comment]
Maybe it's not a quick practical solution, but shouldn't all the other functions actually return igraph_error_type_t?

**Comment by ntamas** [comment]
There was a proposal earlier (from Vincent or me, can't remember) that we introduce `igraph_error_t` as a typedef to `int`, and then we can make it explicit which functions return an error code. This would be my preferred direction instead of replacing genuine `int`s with `igraph_integer_t`.

**Comment by ntamas** [comment]
FYI, `doxrox` include bug is fixed in `4cd9dadee`

**Comment by GroteGnoom** [comment]
> There was a proposal earlier (from Vincent or me, can't remember) that we introduce `igraph_error_t` as a typedef to `int`, and then we can make it explicit which functions return an error code. This would be my preferred direction instead of replacing genuine `int`s with `igraph_integer_t`.

Why doesn't `igraph_error_type_t` suffice?

**Comment by szhorvat** [comment]
Vincent's proposal was to use `igraph_error_type_t`, but that was trouble to use last time I tried. I don't recall all the reasons but one reason was that C++ doesn't allow freely mixing integer values with enums, so it was very cumbersome to change it everywhere.

That's when Tamás suggested the typedef.

**Comment by szhorvat** [comment]
Regarding those `int`s: when we transition to a wide `igraph_integer_t`, I would at the same time transition to a version of CXSparse that can be matched with its integer type. CXSparse supports different integer type widths. Thus at least at that point I would still argue for using `igraph_integer_t` (at least so that we can store more than 2^31-1 elements in a sparse array, i.e. more than that many edges in a graph).

**Pull request merged**
