### PR TITLE
GRAPHML export and locale, aka #930

### PR DESCRIPTION
**Pull request by iosonofabio**
This PR tries to address issue #930 

For now no error handling so the locale might be messed up if anything happens during the XML export.

### CODE REVIEW

**Comment by ntamas** [comment]
Seems good as a starting point, but we should take care of error handling. In particular:

* if `strdup()` returns `NULL`, return `IGRAPH_ENOMEM` and bail out
* otherwise, add `IGRAPH_FINALLY(igraph_free, saved_locale)` right after `strdup()` so `saved_locale` gets freed properly when any of the functions we call return an igraph error code.
* finally, at the end, call `igraph_free()` on `saved_locale` yourself and bump the counter in `IGRAPH_FINALLY_FREE()` by one to clean up the "finally" stack properly

**Comment by ntamas** [comment]
Not quite there yet; `IGRAPH_FINALLY(free, saved_locale)` basically makes a note that if any subsequent `IGRAPH_CHECK()` call returns with an error code, igraph should call `free(saved_locale)` automatically. These entries are stored in a stack which we call the "finally stack". More about this [here](https://igraph.org/c/doc/igraph-Error.html#IGRAPH_FINALLY).

Note that the finally stack is not cleaned if you return from the current function with `return`, so you still need `free(saved_locale)` at the end. For normal return conditions, the idea is that you free everything that you have put in the finally stack on your own, and then you call `IGRAPH_FINALLY_FREE()` and tell igraph how many items to _discard_ from the finally stack (the ones that you have taken care of yourself). If you add a new memory allocation somewhere in a function, you need to:

* add a corresponding `IGRAPH_FINALLY()` call to take care of freeing the memory in case of an error (some macros like `IGRAPH_VECTOR_INIT_FINALLY()` unify the initialization and the handling of the finally stack in a single call).
* free the memory on your own upon normal exit
* find the `IGRAPH_FINALLY_FREE()` call at the end of the normal exit route and bump the counter in it by one

**Comment by iosonofabio** [comment]
This should be good now as soon as tests pass

**Comment by ntamas** [comment]
Seems good to me as well, thanks!

**Pull request merged**
