### PR TITLE
igraph_bridges

### PR DESCRIPTION
**Pull request by szhorvat**
A function to find bridges in the graph. An edge is a bridge if its removal disconnects the graph.

Based on https://www.geeksforgeeks.org/bridge-in-a-graph/

### CODE REVIEW

**Comment by ntamas** [comment]
Seems good -- please add some tests and then I'll be happy to merge it.

**Comment by szhorvat** [comment]
Changes:

 - more cross references in the documentation
 - added a simple test

**Comment by ntamas** [comment]
`src/cs/cs.h` has a `CS_MAX` macro. igraph itself does not have its own variant. If you need one, feel free to add it; `src/igraph_math.h` seems to be a good candidate as it is not part of the public API so we don't provide yet-another-max-macro needlessly.

**Comment by ntamas** [comment]
Can I merge this or do you plan to add something else?

**Comment by szhorvat** [comment]
You can merge it.

**Comment by ntamas** [comment]
Thanks!

**Pull request merged**
