### PR TITLE
Properly fix path problems with CTest on MinGW

### LINKED ISSUE #1501: CMake: when building a shared library, tests don't run on MSYS2
When building a shared library, tests don't run on MSYS2 due to `libigraph.dll` not being present on the `PATH`.

@vtraag I thought you mentioned fixing this recently, but maybe I misremembered.

### PR DESCRIPTION
**Pull request by vtraag**
This is a continuation of #1504. There were some further problems with paths on MinGW, see https://github.com/igraph/igraph/issues/1501#issuecomment-717322063 for some more details. This now finally properly fixes #1501.

### CODE REVIEW

**Comment by vtraag** [comment]
Sorry, I now realise that we should document this monstrosity properly. I unfortunately don't have time now anymore, I have to go.

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
Let's wait for the CI tests; if they pass, I'm okay to merge this.

**Comment by vtraag** [comment]
I now tried to rerun this locally in MinGW to double check something. I rebased against the latest `cmake` branch before opening this PR (without testing actually), but I am now running into several errors similar to the following:

```
C:/Users/traagva1/src/igraph/src/adjlist.c:95:5: error: 'igraph_adjlist_init' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
   95 | int igraph_adjlist_init(const igraph_t *graph, igraph_adjlist_t *al,
      |     ^~~~~~~~~~~~~~~~~~~
```

I don't know immediately what commit caused this, I think this might have been a warning instead of an error earlier.

**Comment by ntamas** [comment]
This is probably unrelated so let's keep track of it in a separate issue.

The doc generation fails now, but that's also another issue, I'll fix it soon.

**Pull request merged**
