### PR TITLE
Add igraph_write_graph_lgl example

### PR DESCRIPTION
**Pull request by GroteGnoom**
Part of #1592

### CODE REVIEW

**Comment by GroteGnoom** [comment]
```
287/288 Test #288: igraph_read_graph_gml_invalid_inputs ......***Failed    0.05 sec

=================================================================
==12515==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 4 object(s) allocated from:
    #0 0x7efdf0098d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x55742ec40d73 in igraph_i_gml_get_keyword /home/vsts/work/1/s/src/io/gml-parser.y:162
    #2 0x55742ec424b5 in igraph_gml_yyparse /home/vsts/work/1/s/src/io/gml-parser.y:140
    #3 0x55742ec3b223 in igraph_read_graph_gml ../src/io/gml.c:209
    #4 0x55742ec2d0f5 in test_file ../tests/regression/igraph_read_graph_gml_invalid_inputs.c:37
    #5 0x55742ec2d23f in main ../tests/regression/igraph_read_graph_gml_invalid_inputs.c:69
    #6 0x7efdef84cbf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 4 allocation(s).
```
I'm guessing I'm not handling the names and weights correctly.
Is it normal this shows up at a different test?

**Comment by ntamas** [comment]
The failure above is unrelated; it's in the GML parser. It has already been fixed in `develop` so if you rebase your PR on the most recent `develop` revision (or merge `develop` into it), it should go away.

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
Thanks a lot!

**Comment by GroteGnoom** [comment]
> Thanks a lot!

You're welcome :) This is a very nice project to work on.

**Pull request merged**
