### PR TITLE
added Alpine Linux test run to Travis CI

### PR DESCRIPTION
**Pull request by iosonofabio**
I added a chroot into Alpine linux as suggested in the open issue #1070 

Currently one test only fails: conversion from sparse to dense matrix.

I'm trying to get the exact log out but the chrooting seems to interfere a little

### CODE REVIEW

**Comment by iosonofabio** [comment]
I tried all kinds of bisections on test 27, i.e. conversions between sparse and dense matrices, but can't for the best of me diagnose the problem. If anyone could have a look that'd be fantastic!

**Comment by ntamas** [comment]
I'll try to reproduce this in Docker on an `alpine` image.

**Comment by ntamas** [comment]
I think https://github.com/igraph/igraph/commit/f6797e82fa984980e1a3a1336a0537eb195f4cac fixes this.

**Comment by iosonofabio** [comment]
Should be fine I think

**Comment by ntamas** [comment]
Tests seem to pass in CI -- is this ready to merge?

**Comment by iosonofabio** [comment]
The only thing is I'm not sure if the `after_failure` trigger works correctly from inside the `chroot`. The CI fails alright when at least one test fails, but it causes an exclamation mark instead of an X. Do you have any clue what this could be? Maybe an exit code in bash?

**Comment by ntamas** [comment]
Hmmm, good point. I think the Travis policy is to mark the build as "errored" if any of the commands in the build steps returns a non-zero exit code, _except_ the script section, where a non-zero exit code would simply indicate a test failure.

**Comment by ntamas** [comment]
Do you have a link to a recently failed Travis build that errored out? I can't find one in the build history in my account.

**Comment by iosonofabio** [comment]
This would be one:

https://travis-ci.org/github/igraph/igraph/jobs/702599842

It says the test failed unexpectedly, but fails to show the log...

**Comment by ntamas** [comment]
Okay, this is totally a stab in the dark, but basically Travis marks the build as "errored" if there is an error in the `before_install`, `install` or `before_script` phases (i.e. any command that is invoked in these stages returns with a non-zero error code). Any non-zero error code in the `script` phase should mark the build as "failed". The reason why this build is marked as "errored" _might_ be because you invoke the build command via `alpine()`, which is a function that you defined in the `install` phase. Try invoking `make check` without using the function defined in the `install` phase, or re-define it in the `script` phase.

**Comment by iosonofabio** [comment]
I redefined the function in the script phase, but it still errors with an exclamation mark instead of a cross, so it does not trigger the `after_failure`. I'll try asking Travis folks...

**Comment by iosonofabio** [comment]
Alright, it seems like `set -e` messes up the Travis error codes. They had a bug report in 2013 which they seem to have fixed, but there must be something still broken about that...

either way it's fixed now, ready for merge

**Comment by ntamas** [comment]
Thanks a lot!

**Pull request merged**
