### PR TITLE
add NCOL read/write consistency test

### PR DESCRIPTION
**Pull request by GroteGnoom**
Fixes part of #1922

### CODE REVIEW

**Comment by szhorvat** [comment]
Could we compare the graph that was read back with the original using `igraph_is_same_graph()`?  In order to do so, we will need to order the vertices identically. We can ensure identical vertex order using the following canonicalization process:

 1. Find the permutation that puts the vertex names in lexicographic order
 2. [Invert that permutation ...](https://github.com/igraph/igraph/issues/1930)  `igraph_vector_int_order` will effectively do the inversion.
 3. Use `igraph_permute_vertices()` to reorder the graph vertices

After having done this both for the original graph, as well as the graph that was read back, we can compare them using `igraph_is_same_graph()`.

**Comment by GroteGnoom** [comment]
Could you explain why? Because it's more readable than a graphml? Or could there be information in there that we're not seeing now?

**Comment by szhorvat** [comment]
I asked for this type of test after I modified the NCOL writer to write edges in a different order and introduced a bug, associating weights with the wrong edges (the bug was never pushed). I am looking for a test which can detect this type of bug.

This modification, even if bug-free, would change the GraphML output here. Then the output would need to be verified _manually_, diminishing the usefulness of the test.

I was looking for a test that verifies that the graph does not change after writing it to a file and reading it back again. The test should fail if and only if the graph that is read back is not identical to the original graph. It should not fail if, for example, the edge or vertex ordering changes.

**Comment by szhorvat** [comment]
> The test should fail if and only if the graph that is read back is not identical to the original graph. It should not fail if, for example, the edge or vertex ordering changes.

This is really what I'm looking for. "Identical" here means having the same edges and vertices, with correct attribute assignments. Any solution that achieves this is fine for me.

**Comment by GroteGnoom** [comment]
I've replaced the graphml write with the is_same_graph, but then checking for attributes separately doesn't seem easy. To compare edge attributes, you need to know which edge in graph1 corresponds to which edge in graph2. is_same_graph uses the internal representation of graphs for that.

Also doesn't is_same_graph still fail if the vertex ordering changes? It uses an ordered list of edges, but they're ordered by the second vertex.

**Comment by szhorvat** [comment]
Could you rebase on current develop and make sure that the test still passes? This doesn't quite do everything I wanted, but I think we can improve it later. It would be useful to merge it as it is.

**Comment by szhorvat** [comment]
I changed it to `abort()` instead of `exit(1)`. The reason is that if the program exits normally using `exit()`, without freeing all memory, LSan will complain about memory leaks. If it exits with `abort()`, it will be considered an abnormal exit, and there won't be distracting messages about memory leaks.

**Pull request merged**
