### PR TITLE
Bitset improvements and more bitset usage

### PR DESCRIPTION
**Pull request by szhorvat**

### CODE REVIEW

**Comment by szhorvat** [comment]
@Tagl Can you review this please?

**Comment by szhorvat** [comment]
The failure on Travis is real. Something might be wrong with bitsets on s390x. This needs to be checked before merging.

**Comment by szhorvat** [comment]
It's fixed now, it was a silly mistake on my part.

**Review by Tagl — COMMENTED** [review]
Looks good as far as I can tell. Have you benchmarked anything yet?

**Comment by szhorvat** [comment]
> Looks good as far as I can tell. Have you benchmarked anything yet?

I benchmarked several functions, and none of them show a noticeable change in performance. I'll consider that a win, as memory usage has been reduced, sometimes considerably.

**Comment by Tagl** [comment]
> > Looks good as far as I can tell. Have you benchmarked anything yet?
> 
> I benchmarked several functions, and none of them show a noticeable change in performance. I'll consider that a win, as memory usage has been reduced, sometimes considerably.

That makes sense and absolutely it is a win. Some of functions changed can probably be improved upon furhter by utilizing bitmasks in some way and then a speed increase will be noticeable. But this is already good!

**Review by Tagl — APPROVED** [review]

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
Thanks!

**Pull request merged**
