### PR TITLE
igraph_sir: interruption support and other fixes

### PR DESCRIPTION
**Pull request by szhorvat**
Please see commit messages for details.

### CODE REVIEW

**Comment by ntamas** [comment]
Seems like a tug-of-war between `xz` and `zip` (well, their dependencies). Guess we could remove `xz` from the default installation as we don't need it, but I expect this to be a temporary problem.

By the way, the commits seem okay for me.

**Comment by szhorvat** [comment]
Please wait with merging, there's an occasional crash with the interruption.

**Comment by szhorvat** [comment]
OK, the problem was that `igraph_i_sir_destroy` did not set the destroyed `vector_ptr` elements to `NULL`. Therefore the caller could not detect that some elements should not be destroyed when an interruption occurred.

The fix was a bit ugly because I had to get rid of the `s` variable. Alternatively, I could have made used an `igraph_sir_t **s`, but then the compiler warns about incompatible pointer types (since assigning from a `void **`). I don't see any alternative. @ntamas ?

I also added two other commits.

**Comment by szhorvat** [comment]
Just clearing the `vector_ptr` at the end of `igraph_i_sir_destroy` would have been simpler, I guess ...

**Pull request merged**
