### PR TITLE
fix: Replace check of constant with a static assertion

### PR DESCRIPTION
**Pull request by krlmlr**
Should the new `IGRAPH_STATIC_ASSERT` find a better home?

This is needed to avoid `R CMD check` warnings in R.

### CODE REVIEW

**Comment by krlmlr** [comment]
@GroteGnoom: `IGRAPH_STATIC_ASSERT()` currently lives in `hacks.h` . How to promote it so that we can use it internally but it's not exposed to the outside world?

**Comment by ntamas** [comment]
Should we use it at all? It's a horrible hack whose only aim is to simulate `static_assert(...)` in pure C. If we can safely assume that the R interface is always compiled with a C++11 compiler, then we can simply use `static_assert(...)`.

How about this? We wrap `IGRAPH_STATIC_ASSERT` with an `#ifndef` block in `hacks.h`, thus allowing the user to override it. Then, in the R interface, we simply `#define IGRAPH_STATIC_ASSERT static_assert`.

**Comment by krlmlr** [comment]
Can we add a `cmake` rule? The R client could pick it up from there: https://github.com/igraph/rigraph/issues/1189#issuecomment-1975602925

**Comment by krlmlr** [comment]
Also, I feel these are two separate points:

1. How to use `IGRAPH_STATIC_ASSERT()` in this macro
2. How to implement `IGRAPH_STATIC_ASSERT()`

**Comment by ntamas** [comment]
CMake already has a variable for checking whether the compiler has static assert support; see the `cxx_static_assert` flag [here](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html). The problem is that we cannot simply replace `IGRAPH_STATIC_ASSERT` with `static_assert` in the C core because you cannot use ` static_assert` in C files.

Why does `R CMD check` complain about `IGRAPH_STATIC_ASSERT` at all?

**Comment by krlmlr** [comment]
The CI/CD here complains about not finding `IGRAPH_STATIC_ASSERT()` . How to fix idiomatically?

**Comment by krlmlr** [comment]
AFAIU, `IGRAPH_STATIC_ASSERT()` is how you implement static assertions in C. We need that in C code. I'd not count it as a hack.

`R CMD check` complains about checking a condition that is always true.

**Comment by szhorvat** [comment]
This modification makes it invalid to use `NULL` for `code`. That is not unreasonable, since we'd always want to store the return code and check for `IGRAPH_STOP`.

I would skip the `IGRAPH_STATIC_ASSERT`, it's not strictly necessary. It's implementation is hack (with no better substitute) so I wouldn't want to expose it in a public header.

**Comment by ntamas** [comment]
I don't mind exposing `IGRAPH_STATIC_ASSERT` in public headers. It seems portable enough. We can add it in a public header that is not included from `igraph.h` but has to be included explicitly.

**Comment by krlmlr** [comment]
I'd need help with that.

**Comment by ntamas** [comment]
Would that help if I moved the macro to a public header in the `master` branch?

**Comment by krlmlr** [comment]
Yes, please. Thanks!

**Comment by ntamas** [comment]
https://github.com/igraph/igraph/commit/a4f6a43c162bd68ac3b8db00b2b0a5d1c7855415

**Comment by ntamas** [comment]
I'm not really worried about it. C11 has `_Static_assert()` anyway so it's only a concern for compilers that support C99 but not C11; we can switch to `_Static_assert()` for C11 if we want to.

**Comment by szhorvat** [comment]
It seems to me that nothing more needs to be done here. Please re-open if I'm mistaken.

**Comment by szhorvat** [comment]
I'm sorry, this is not actually done. @krlmlr @ntamas can you please complete it so we can merge and close?

**Comment by ntamas** [comment]
I decided to remove the `IGRAPH_STATIC_ASSERT` block entirely from the expansion of `IGRAPH_CHECK_CALLBACK`, the reason being that having it there would require the user to `#include "internal/hacks.h"`. Essentially we were providing a macro in a public header that does not work without the additional inclusion of a private header.

Let's see if the CI passes and then I'll merge.

**Comment by szhorvat** [comment]
> Essentially we were providing a macro in a public header that does not work without the additional inclusion of a private header.

You did add `IGRAPH_STATIC_ASSERT` to a public header though. Do we keep it there then?

(No strong opinion from me, but if you do ask me, I'd not make it public because it's essentially a hack.)

**Comment by ntamas** [comment]
> You did add IGRAPH_STATIC_ASSERT to a public header though. Do we keep it there then?

No, that's exactly the point of my last commit: `IGRAPH_STATIC_ASSERT` is not referred to from any public headers any more.

**Comment by szhorvat** [comment]
I think we have a misunderstanding.

You recently moved `IGRAPH_STATIC_ASSERT` to a public header, `igraph_misc.h`. It is still in that header now, and NOT in `internal/hacks.h`. Do we really want to keep it there, or do we move it back to an internal header?

This was your commit: https://github.com/igraph/igraph/commit/a4f6a43c162bd68ac3b8db00b2b0a5d1c7855415#diff-b884378d5b5db1523e2a568f53c474a82e0e257c9cee570ff2beed88dd8cd706

I am in favour of moving it back to the internal header. I don't want to commit to supporting the use of this macro for general users.

**Comment by ntamas** [comment]
Hmmm yeah, strange, I was looking at the source tree in this PR and here the macro was definitely in `src/internal/hacks.h`. Okay, let's revert `a4f6a43`

**Comment by szhorvat** [comment]
Can you please do that, and before you push, make sure that headers are updated for any more recently added usages of `IGRAPH_STATIC_ASSERT` (such as the one I added yesterday)?

**Pull request merged**
