### PR TITLE
igraph_rewire_directed_edges

### PR DESCRIPTION
**Pull request by szhorvat**
This is a pull request for the feature described in #999 

The function is modelled after igraph_rewire_edges and borrows some code from it.  Please review especially the part that handles attributes, as I am not very familiar with this part of igraph, and the code has simply been borrowed from `igraph_rewire_edges`.

### CODE REVIEW

**Comment by szhorvat** [comment]
Do you guys prefer a warning for when `mode != IGRAPH_ALL` and the graph is undirected?

**Comment by gaborcsardi** [comment]
> Do you guys prefer a warning for when mode != IGRAPH_ALL and the graph is undirected?

No, no warning is necessary.

**Comment by szhorvat** [comment]
Do you need me to do anything else with this one before it can be merged?

**Comment by ntamas** [comment]
I'll try to find some time to review this and your other PRs this week and then I'll merge it.

**Comment by szhorvat** [comment]
Do you need anything else from me before this can be merged?

**Comment by ntamas** [comment]
Sorry, probably nothing, apart from time, which is not your concern of course. I'm just way too much behind with everything else.

**Comment by szhorvat** [comment]
This is currently okay to merge. I would like to sync up my fork with the official igraph, but it just keeps drifting apart (mostly due to me having started too many unfisnished PRs)

**Comment by ntamas** [comment]
Seems good, thanks!

**Pull request merged**
