### PR TITLE
Fix appveyor test execution.

### PR DESCRIPTION
**Pull request by ObiWahn**

### CODE REVIEW

**Comment by ObiWahn** [comment]
Build execution time has reached the maximum allowed time for your plan (60 minutes).

There could be UB in one of the tests. Maybe somebody with a windows system could further inspect the issue.

**Comment by ObiWahn** [comment]
Just one test failing:)

**Comment by ObiWahn** [comment]
Is there hope to get this merged?

**Comment by ntamas** [comment]
Can you please provide a description about what issues this PR is supposed to fix? Note that the `feature/cmake-build` branch has diverged from yours a while ago so it is possible that some of the issues are already fixed.

**Pull request closed without merging**
