### PR TITLE
Start working on betweenness cutoff=0 #1050

### PR DESCRIPTION
**Pull request by iosonofabio**
Changing an `>= 0` into `> 0` should work, as the doc says. Of course, as already noted in #1050, there's no good reason to set `cutoff = 0` except to get exact betweenness.

### CODE REVIEW

**Comment by iosonofabio** [comment]
I think this is done. I understand this is planned for 0.9 but since it's done we could include it already

**Comment by szhorvat** [comment]
Please also change the weighted case, as well as the edge betweenness case (only the weighted calculation is affected for that one).

Have you tested the change already?

**Comment by iosonofabio** [comment]
Thank you @szhorvat, I can write a test for CI.

Are those other things mentioned in other issues on GitHub? If so it'd be great to collect them all here so I can understand the situation better and close them at once.

**Comment by szhorvat** [comment]
I mentioned them in #1050:

 - unweighted and weighted vertex betweenness is affected
 - weighted edge betweenness is affected
 - unweighted edge betweenness is not affected

The same fix you applied should work for the missing two as well.

**Comment by szhorvat** [comment]
I just verified that closeness calculation is not affected (but found another problem there ... will open an issue).

**Comment by iosonofabio** [comment]
You mean issue #56?

**Comment by szhorvat** [comment]
Sorry, I'm not sure I understand. Are you referring to the closeness issue I mentioned? It's #1197

**Comment by iosonofabio** [comment]
My fault, wrong link 😋

The closeness is a separate regression bug, the weighted version I'm not sure but I don't have my computer now, let me check and get back to you 😊

**Comment by szhorvat** [comment]
Yes, the closeness is independent and unrelated. I simply confirmed that there is no issue with the cutoff parameter and closeness calculations. The only problems are with 3 varieties of betweenness, see my message above. https://github.com/igraph/igraph/pull/1187#issuecomment-496248605

**Comment by iosonofabio** [comment]
Good, I fixed the two remaining betwennness measures.

Anything else I should do about this?

Shall we just wait until the checks pass on CI or shall I make a test against this corner case?

**Comment by szhorvat** [comment]
In my personal experience, it is very important to test (= try out) every change one makes.  I do not mean adding a test case, but did you actually try it out? Often the easiest way is to build a high-level interface with the change and try it from that.

**Comment by iosonofabio** [comment]
Agreed. Then I would need to compile python-igraph against the locally built C core and then write a short Python script against that I guess. Is there any info on how to do that?

**Comment by iosonofabio** [comment]
Ok I added tests for the vertex and edge betweenness, both for weighted and unweighted. They work fine, so the PR is good to go.

**Comment by ntamas** [comment]
> I would need to compile python-igraph against the locally built C core

Personally, I do it like this:

1. Install `pkg-config` and add `$HOME/lib/pkgconfig` to the environment variable named `PKG_CONFIG_PATH`. (I have this in my shell profile).
2. Add `$HOME/lib` to `LD_LIBRARY_PATH` (or to `DYLD_LIBRARY_PATH` on macOS). This is to ensure that libraries installed in `$HOME/lib` are picked up by the linker.
3. Build and install igraph locally with `mkdir build && cd build && ../configure --prefix=$HOME && make && make install`. This installs igraph in `$HOME/include/igraph/...` and `$HOME/lib`, and also puts a file in `$HOME/lib/pkgconfig` that helps `pkg-config` tell what the igraph compiler and linker flags are. (You can validate this with `pkg-config --cflags --libs igraph`).
4. Check out `python-igraph`'s source code somewhere and then run `python setup.py install`. (Preferably in a virtualenv to avoid messing around with the system Python).

Let me know if you need more help with this.

**Comment by iosonofabio** [comment]
Thank you, we should write this up in some docs...

**Pull request merged**
