### PR TITLE
Improvements to CI

### LINKED ISSUE #1387: CI tests with x87 math
Given the problems we had with the test suite on Debian running on non-common platforms, it would be useful to add CI tests that use x87 math (not SSE). This can be done in 64-bit mode, using the compiler flag I showed in #1371 (`-mfpmath=387`). @ntamas, opinions?

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #1387 

Changes:

 - Build with external GLPK for a small speedup
 - Remove stages and use only jobs for full parallelization (i.e. test doc build in parallel)
 - Test with 80-bit x87 floating-point arithmetic (currently reveals failures)
 - Identify each job by name

### CODE REVIEW

**Comment by szhorvat** [comment]
I just added build parallelization using `make -j2`, [as recommended by Travis](https://docs.travis-ci.com/user/speeding-up-the-build/#makefile-optimization). This comes with the disadvantage of messing up the output order, so I'm not sure we want it. Let me know what you think.

The overall run time came down from 10:43 to 7:32, mostly due to the Mac build. I'm not sure that's worth it.

Non-parallel build:

image

Parallel build (`make -j2)`:

image

**Comment by ntamas** [comment]
Seems OK for me -- apart from the test failure of course.

Regarding the output order: to be honest, I hardly ever look at the detailed CI logs if there is a failure, so I don't mind if the output is messed up a bit. However, I _do_ mind waiting for 20 mins for the results of a CI build, especially when merging a PR.

**Comment by ntamas** [comment]
Shall I merge this or do you want to work on this further?

**Comment by szhorvat** [comment]
Go ahead and merge.

If you have time, can you also merge into `develop`? Merging master into develop will need resolving the conflict from #1341

**Comment by ntamas** [comment]
#1341 conflicts with `feature/cmake-build`, not with `develop`.

`develop` should now be up-to-date with `master`.

**Comment by szhorvat** [comment]
oops, you're right!

**Pull request merged**
