### PR TITLE
Add layout graphopt unit tests

### PR DESCRIPTION
**Pull request by GroteGnoom**
I changed the interface of graphopt, because I though it would be clearer and would not lead to any actual interface changes. As far as I can tell the same thing should happen for the same arguments (except maybe less overflows if igraph_integer_t is bigger than int).

### CODE REVIEW

**Comment by szhorvat** [comment]
It is very strange that the spring length is treated as an integer internally. As any physical length, it should be a real number. @gaborcsardi do you recall why it's so?

Here is the original graphopt: http://www.schmuhl.org/graphopt/  From a quick (and not very careful) look, my best guess is that this was made an integer so that it would be easy to adjust through a spinbox GUI.

I would propose the opposite: keep the interface as is and change all internal `spring_length` variables to real numbers.

**Comment by gaborcsardi** [comment]
I don't remember, sounds good to me.

**Review by szhorvat — APPROVED** [review]

**Comment by ntamas** [comment]
> I would propose the opposite: keep the interface as is and change all internal spring_length variables to real numbers.

What's the status of this? In the PR it is still an `igraph_real_t` but now we have a stamp of approval :) I don't mind either way, there will be API breakages in 0.10 anyway.

**Comment by szhorvat** [comment]
@ntamas Previsouly it was a `real` in the API, but it was an `int` internally. Now it is a `real` internally as well. I looked through the code and I could see no reason to avoid a real. I think the original code used an `int` because the parameter was tied to a GUI control that can only set integers.

I approved but didn't merge because I thought we might want to merge most of the new tests into `master` now (unless the API had to be changed or the behaviour was changed significantly). It's very easy to rebase right here on GitHub.

**Comment by ntamas** [comment]
Okay, let's merge this into `master` then! Can you do the rebase and merge?

**Pull request merged**
