### PR TITLE
Write example for igraph_full

### PR DESCRIPTION
**Pull request by iosonofabio**
Fixing #1200 with a few examples for undirected/directed full graphs with and without self loops.

### CODE REVIEW

**Comment by ntamas** [comment]
Not sure whether this is really meant as an example or as a test case. If we don't have a test case for `igraph_full()` yet, maybe it's worth moving (or copying) this to `examples/tests/` and check whether the graph that was created is indeed a full graph? (Printing the edge list to a file and providing an `.out` file for the test case would be enough I think).

**Comment by iosonofabio** [comment]
Alright, I copied the file into `example/tests` and added checks that the edges are really there with an output file. I think we can merge now?

**Comment by szhorvat** [comment]
Once again, tab-indentation and space-indentation are being mixed randomly.

**Comment by iosonofabio** [comment]
Indeed, my editor fixes it for me. Please feel free to improve my humble, incorregible habits.

**Comment by szhorvat** [comment]
You can use `print_graph` from `test_utilities.inc` to output the graph.

Please always add `VERYIFY_FINALLY_STACK();` at the end of tests.

**Comment by iosonofabio** [comment]
Yes, added the verify statement at the end of the test.

**Pull request merged**
