### PR TITLE
[master/autoconf] add github workflow for MSYS2's MINGW32 and MINGW64

### PR DESCRIPTION
**Pull request by jannick0**
This is meant as a start for CI runs on MSYS2.

### CODE REVIEW

**Comment by jannick0** [comment]
We should add branch restrictions for CI builds using autoconf.  Is there any rule in terms of branch names or is `master` the only one to run this workflow on?

**Comment by ntamas** [comment]
`master` is the only remaining autoconf-based branch; all other branches will be based on CMake. (We have lots of dead branches that we are not going to touch, we can leave them as they are).

**Review by ntamas — APPROVED** [review]

**Comment by jannick0** [comment]
Many thanks for merging!

@ntamas @szhorvat I believe we need to finetune as to when pushes to branches **on a fork** of this repo should fire up the github workflow - and/or the other CIs. Here a suggestion for a **simplistic** branch name nomenclature triggering the various CIs (let's keep it really stupid and simple):
* `master/appveyor/<branch>` - run appveyor CI only
* `master/msys/<branch>` - run the msys github workflow only
* `master/travis/<branch>` - run travis CI only 
* `master/<branch>` - run all CIs above


Agree? Any other suggestions?

Happy to put this in place. Likewise for the `develop` branch (instead of `master`), of course.

**Comment by jannick0** [comment]
Just discovered that `git` dislikes slashes in branch names. So let's replace them above by, say, hyphens (e.g. `master-appveyor-<branch>`).

**Comment by ntamas** [comment]
> Just discovered that git dislikes slashes in branch names. 

Does it? I routinely use Git Flow styled branch names like `feature/some-fancy-feature` or `fix/some-annoying-bug` (without actually sticking to the Git Flow toolset). What should I have noticed?

The proposed naming scheme is okay for me.

**Comment by jannick0** [comment]
> > Just discovered that git dislikes slashes in branch names.
> 
> Does it?

Actually no - git does like slashes. I got trapped by a glitch of the git viewer I am using. Happy to go with slashes then.

> The proposed naming scheme is okay for me.

I'll shoot a PR shortly - for the `develop` branch, too.

**Pull request merged**
